### ISSUE TITLE
Request to Add TimeMixer Model to neuralforecast Project

### ISSUE THREAD

**Issue by kwuking** [Nixtla/neuralforecast#1016]
### Description

Request to Add TimeMixer Model to neuralforecast Project

### Use case

Dear Maintainer,

I hope this message finds you well.

I am writing to you regarding your excellent work on the neuralforecast project, which provides scalable and user-friendly neural forecasting algorithms. Your contributions to the field are highly appreciated and have been incredibly valuable to the community.

We recently presented our work at ICLR 2024 on a new model called TimeMixer: Decomposable Multiscale Mixing for Time Series Forecasting. This model leverages a decomposable multiscale mixing mechanism, achieving significant improvements in time series forecasting performance and demonstrating superior results across various benchmark tests.

Given the alignment of our work with the goals of the neuralforecast project, we would be honored if you could assist us in adding the TimeMixer model to the neuralforecast project. We believe that incorporating TimeMixer will further enhance the repository, providing the community with more options and stronger predictive capabilities.

The GitHub repository for TimeMixer can be found at the following link: https://github.com/kwuking/TimeMixer.

If you have any questions or require additional technical details, please do not hesitate to reach out. We are more than willing to provide any necessary support and assistance.

Thank you very much for your consideration and support. We look forward to your positive response.

**Comment by kwuking** [comment]
@JQGoh  Thank you for your support and assistance with our request. Here, we followed the approach of the Time-Series-Library project. Specifically:
1.  In [TimeFeatureEmbedding](https://github.com/kwuking/TimeMixer/blob/9f7311df399a47408e9e95036dfbe949e67759db/layers/Embed.py#L100-L101), the freq_map dictionary maps different time frequencies to an integer value, which represents the input dimension d_inp. For 'a' (representing year), d_inp is set to 1. This is because, in most time series analyses, the year is usually represented as a single value. For example, the year 2024 can be represented by a single integer.

Specifically, the value of d_inp determines the dimensionality of the input features. For example:

- 'h' (hour) is mapped to 4, possibly because hourly features might include hour, minute, second, and millisecond, covering multiple dimensions.
- 'd' (day) is mapped to 3, possibly because daily features might include year, month, and day, covering three dimensions.
- 'a' (year) is mapped to 1 because the year usually requires only a single value for representation.

Therefore, for yearly frequency, setting the input feature dimension d_inp to 1 is reasonable because the year typically only needs one value for representation, without requiring additional dimensions. This approach simplifies the model's input and reduces computational complexity.

2. For [TemporalEmbedding](https://github.com/kwuking/TimeMixer/blob/9f7311df399a47408e9e95036dfbe949e67759db/layers/Embed.py#L66-L93), indeed, the embed_type is set to fixed here. Currently, we are using the same settings as the Time-Series-Library project.

Once again, we express our gratitude for your help and support. If you have any further questions, please feel free to contact me.

**Comment by kwuking** [comment]
@JQGoh Hi, are there any issues with TimeMixer at the moment? Thank you for your attention to TimeMixer. If you have any questions, please feel free to contact me at any time.

**Comment by kwuking** [comment]
> @kwuking Most recently I got new tasks assigned that I need to prioritize them. I expect to have more bandwidth during July.
> 
> I will keep you updated again when I am ready.


Thank you very much for your help and support. We are looking forward to your progress. If there are any updates or if you have any questions, please don't hesitate to contact me. I noticed that you have also added our Time-LLM to neuralforecast. Once again, I would like to express my gratitude and regards to you.

**Comment by marcopeix** [comment]
@kwuking Thank you for reaching out and for the great work on Time-LLM and TimeMixer. Right now, I am working on implementing the model in neuralforecast, but I am running into an issue that I still can't figure out.

In `MultiScaleSeasonMixing`, in the `forward` method, we have 

``` python
out_high = season_list[0]
out_low = season_list[1]
```

However, `season_list` has only one element. I'm testing the model on the Air Passengers dataset for quick prototyping. Any idea what I could be missing?

**Comment by kwuking** [comment]
> @kwuking Thank you for reaching out and for the great work on Time-LLM and TimeMixer. Right now, I am working on implementing the model in neuralforecast, but I am running into an issue that I still can't figure out.
> 
> In `MultiScaleSeasonMixing`, in the `forward` method, we have
> 
> ```python
> out_high = season_list[0]
> out_low = season_list[1]
> ```
> 
> However, `season_list` has only one element. I'm testing the model on the Air Passengers dataset for quick prototyping. Any idea what I could be missing?
> 
> Code is [here](https://github.com/Nixtla/neuralforecast/blob/feature/timemixer/nbs/models.timemixer.ipynb) (still a work in progress)

Thank you very much for your interest in and dedication to our work. I checked the code and found that some important parameters, specifically down_sampling_layers and down_sampling_window, are missing. Since TimeMixer is a multi-scale mixing model, it requires sampling the original input sequence at different scales to generate sequences of different scales. Hence, the absence of these two important parameters could potentially lead to issues. Thank you once again for your effort. If you have any questions, please feel free to contact me at any time.

**Comment by marcopeix** [comment]
Oh, I found my mistake! One of the down sampling parameter was set to 0, which resulted in the bug! Thank you so much for your help! TimeMixer should be available soon!

**Comment by kwuking** [comment]
> @marcopeix Since you have started to work on this, we shall look forward to your implementation! Unfortunately, I did not have enough time in the past month that I cant contribute to this.
> 
> I have a couple of small requests and questions:
> 
> 1. Could you help to simplify the codes in NeuralForecast by recycling some commonly used functions, such that we do not duplicate the same codes? Please refer to https://github.com/Nixtla/neuralforecast/pull/1020/files and check how I moved functions such as `SeriesDecomp`, `MovingAvg`. These functions can be recycled to be part of the implementation of `TimeMixer` as well. Regarding the mentioned PR, you can ignore the [introduction of `fixed_weight` to the class of `PositionalEmbedding`](https://github.com/Nixtla/neuralforecast/pull/1020/files#diff-8be701bd7e9b4b097a136ac5b06c0d838a7dd79b9c485e209e0ba9cbf796cb7bR374), as I am concerned this results in backward compatibility issue during prediction (model trained in old version will fail during prediction)
> 2. In the implementation of `DFT_series_decomp`, could you revise `top_k_freq, top_list = torch.topk(freq, 5)` -> `top_k_freq, top_list = torch.topk(freq, self.top_k)` such that the parameter `top_k` can be effective. Otherwise, the hard-coded `5` will fix the DFT_series_decomp behavior. @kwuking Please take note about the hard-coded `5` in your original implementation, correct me if this is designed on purpose
>    https://github.com/kwuking/TimeMixer/blob/main/models/TimeMixer.py#L22
> 3. Lastly, I considered using `BaseWindows` for the implementation, meanwhile you used `BaseMultivariate`. May I check what is the rationale of using `BaseMultivariate`? Based on my understanding on `TimeMixer` model, it does not require multi-series information (take AirPassengers data set for example, forecasting for Airline1 does not require information from Airline2). What I understood about `BaseMultivariate` is that this is relevant for multi-series forecasting model such that forecasting on a series can make good use of information from the other time-series (that is why we have `n_series` parameter).
> 
> Thanks and look forward to your reply!

I greatly appreciate the strong support from you and @marcopeix  for our work. Your understanding is correct; it should be `torch.topk(freq, self.top_k)`. I will make sure to update the code accordingly. Thank you for your reminder, and please feel free to contact me anytime if you have any questions.

**Comment by marcopeix** [comment]
@JQGoh , thanks for the comments on the PR! It really improved the code. As for the use of BaseMultivariate, it's because the model supports both channel dependence and independence. So, BaseMultivariate by default considers channel dependence, and we can add a flag for channel independence. With BaseWindows, it's channel independence only.

**Comment by marcopeix** [comment]
Hello @kwuking . I'm having some issues including future exogenous variables in TimeMixer. The error occurs with TemporalEmbedding. Basically, when I feed x_mark with shape (1, 1, 24, 2] [batch, n_exog_features, length, n_series], it returns a tensor of shape (1,1,2,32). 

If we don't use exogenous features, it works fine. x_enc has shape (1,24,2) [batch, input_size, n_series] and after TokenEmbedding, we get a tensor of shape (1,24,32). 

Of course, adding (1,24,32) with (1,1,2,32) doesn't work. So is there a bug in TemporalEmbedding or does x_enc_mark have the wrong shape to start with?

Thanks for your help!

**Comment by kwuking** [comment]
> Hello @kwuking . I'm having some issues including future exogenous variables in TimeMixer. The error occurs with TemporalEmbedding. Basically, when I feed x_mark with shape (1, 1, 24, 2] [batch, n_exog_features, length, n_series], it returns a tensor of shape (1,1,2,32).
> 
> If we don't use exogenous features, it works fine. x_enc has shape (1,24,2) [batch, input_size, n_series] and after TokenEmbedding, we get a tensor of shape (1,24,32).
> 
> Of course, adding (1,24,32) with (1,1,2,32) doesn't work. So is there a bug in TemporalEmbedding or does x_enc_mark have the wrong shape to start with?
> 
> Thanks for your help!

Thank you very much for your support. It is necessary to explain here that TimeMixer uses the [TSLib framework](https://github.com/thuml/Time-Series-Library), in which exogenous variables are concatenated with the n_series dimension. After embedding processing, they are directly added together. You can refer to the [Embed-related code](https://github.com/kwuking/TimeMixer/blob/main/layers/Embed.py) in the TimeMixer code repository. The TokenEmbedding does not add new dimensions. If you have any further questions, please feel free to contact me. Once again, I would like to express my gratitude and best regards.

**Comment by kwuking** [comment]
> Hello @kwuking . I'm having some issues including future exogenous variables in TimeMixer. The error occurs with TemporalEmbedding. Basically, when I feed x_mark with shape (1, 1, 24, 2] [batch, n_exog_features, length, n_series], it returns a tensor of shape (1,1,2,32).
> 
> If we don't use exogenous features, it works fine. x_enc has shape (1,24,2) [batch, input_size, n_series] and after TokenEmbedding, we get a tensor of shape (1,24,32).
> 
> Of course, adding (1,24,32) with (1,1,2,32) doesn't work. So is there a bug in TemporalEmbedding or does x_enc_mark have the wrong shape to start with?
> 
> Thanks for your help!

@marcopeix  Hi, has the issue been resolved? If you still have any questions, feel free to contact me anytime.

**Comment by marcopeix** [comment]
Didn't have time to look into it just yet. But it would help a lot if you can contribute with a fix!

**Comment by kwuking** [comment]
> Didn't have time to look into it just yet. But it would help a lot if you can contribute with a fix!

Many thanks for your contribution. I will take some time to debug it soon, and if all goes well, I will submit a pull request.

**Comment by MLfreakPy** [comment]
@kwuking and @marcopeix thank you very much for working on the future exogeneous co-variables fix! Surely, this is a very valuable contribution, considering the importance of future holidays, promotions, and much more.

**Comment by MLfreakPy** [comment]
On a side-note: I have the some issues including _historical_ exogenous variables in TimeMixer.
