### ISSUE TITLE
[<Library component: Model|Core|etc...>] text error

### ISSUE THREAD

**Issue by Raphealshuai** [Nixtla/neuralforecast#1022]
### What happened + What you expected to happen

Report autoformer when I am training fedformer, not a big deal though.

### Versions / Dependencies

![image](https://github.com/Nixtla/neuralforecast/assets/51142577/34b41055-a1ea-4ab4-9446-0cac3e4dff8b)

### Reproduction script

use static variables when training fedformer.

### Issue Severity

None

**Comment by marcopeix** [comment]
Fixed in the latest version of neuralforecast!
