### ISSUE TITLE
nf.predict spam printing in prediction

### ISSUE THREAD

**Issue by dara1400** [Nixtla/neuralforecast#1026]
### What happened + What you expected to happen

I want to use nf.predict in a loop.
It keeps printing this:

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Is there way to stop it from printing?

### Versions / Dependencies

Windows 11, Python 3.10,  neuralforecast v1.7.2

### Reproduction script

```
for i in range(100):
      nf.predict(x[i])
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
```python
import logging
logging.getLogger('pytorch_lightning').setLevel(logging.ERROR)
```
