### ISSUE TITLE
TimeLLM - expand LLM backend support beyond transformers

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [Nixtla/neuralforecast#1038]
### Description

Hello, 

Is it possible to support timeLLM class beyond the current use of HuggingFace transformers package? 

The transformers package is slow and doesn't appear to have acceleration support for Windows + Nvidia (the Optimum package used to to accelerate transformers doesn't support a Windows + Nvidia GPU config as of this writing). 

It'd be great to see timeLLM class work with popular online LLM APIs (OpenAI, Mistral, etc.) and local LLMs via Ollama out-of-the-box.

**Comment by marcopeix** [comment]
TimeLLM needs an embedding-visible LLM, so something like GPT2. That's why we use HuggingFace, so we can access open-source models.
