### ISSUE TITLE
Can I use Exogenous Features with AutoLSTM?

### ISSUE THREAD

**Issue by sm-ak-r33** [Nixtla/neuralforecast#1058]
### Description

I am trying to predict some forecast using the automated hyperparameter tuning from AutoLSTM. I do not see a way how it can be places as input unlike basic nixtla LSTM. Is there any way that can be done? 

Also is there a way to find out the feature importances like MLforecast?

**Comment by sm-ak-r33** [comment]
Also, If I put the exogenous variables as regular columns, would AutoLSTM take these into account for prediction?

**Comment by sm-ak-r33** [comment]
If I just use a historical exogenous list, would I be obliged to provide the future values as well ?

**Comment by jmoralez** [comment]
No, the future values are only required for future exogenous.

**Comment by sm-ak-r33** [comment]
What about the feature importances? Is there a built in way for them to be calculated?

**Comment by jmoralez** [comment]
No, you can subscribe to #637 to track the progress on that.
