### ISSUE TITLE
[core] version 1.7.2 onwards requires a pytorch-lightning version bump to >=2.1.0

### ISSUE THREAD

**Issue by fabianbergermann** [Nixtla/neuralforecast#1079]
### What happened + What you expected to happen

The dependencies are slightly out of date (see title).
Context [here](https://github.com/Nixtla/neuralforecast/pull/974/files#r1691966081)
@jmoralez might I tag you in this one?
Many thanks for the great effort, the package is very much appreciated 🙌 

### Versions / Dependencies

1.7.2

### Reproduction script

installing  neuralforecast version >=1.7.2 with pytorch-lightning ^2.0 will break the code

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Please let me know if you agree with the suggestion https://github.com/Nixtla/neuralforecast/pull/974#discussion_r1691973022 instead of bumping the requirement
