### ISSUE TITLE
Can't import TimeMixer model from neuralforecast

### ISSUE THREAD

**Issue by redaelkate** [Nixtla/neuralforecast#1087]
### What happened + What you expected to happen

after installing neuralforecast I run this code `from neuralforecast.models import TimeMixer` to import the model but I keep getting  importerror :   ImportError: cannot import name timemixer from neuralforecast.models (/usr/local/lib/python3.10/dist-packages/neuralforecast/models/__init__.py)

### Versions / Dependencies

kaggle notebook and google colab

### Reproduction script

from neuralforecast.models import TimeMixer

### Issue Severity

High: It blocks me from completing my task.

**Comment by elephaint** [comment]
Hi,

Our docs have already been updated but TimeMixer is not available yet; we expect to make a release next week which will make TimeMixer available to use.

Sorry for the inconvenience; I'll drop a note as soon as we make the release. To use TimeMixer already, you can git clone the repo and install from source.

**Comment by elephaint** [comment]
@redaelkate We released 1.7.4 today, which contains `TimeMixer`. Hence, if you update neuralforecast (`pip install neuralforecast --upgrade`), you should be able to use TimeMixer. 

Let me know if this works for you.

**Comment by harrisonchan** [comment]
@elephaint I'm confused about the TimeMixer model, are you not able to use future exogenous variables with it?

**Comment by marcopeix** [comment]
We encountered a bug when trying to support future exogenous variables. For now, TimeMixer does not support them, but we are working on including them.

Still, the model is multivariate, so it will considered any inter-dependence between multiple series, and also note that future exogenous variables were not used in the original paper.
