### ISSUE TITLE
How can I close the message output during training and prediction?

### ISSUE THREAD

**Issue by ZhikangLai** [Nixtla/neuralforecast#1101]
### Description

![1723454817797](https://github.com/user-attachments/assets/0487085a-5198-45ef-a8b7-d9223fb6f919)
<img width="1619" alt="1723454851325" src="https://github.com/user-attachments/assets/9a57f2c3-8905-404f-8178-a906d16c786b">

**Comment by jmoralez** [comment]
Add the following before calling fit:
```python
import logging
import ray

logging.getLogger('pytorch_lightning').setLevel(logging.ERROR)
ray.init(log_to_driver=False)
```
For the id warning you have to set the env variable as the message says, but you have to handle the fact that the id will not be in the index anymore:
```python
import os

os.environ['NIXTLA_ID_AS_COL'] = '1'
# don't reset the index on the output from predict if that's what you're currently doing
```

**Comment by ZhikangLai** [comment]
> ```python
> os.environ['NIXTLA_ID_AS_COL'] = '1'
> ```

Thank you. Mr. @jmoralez . It works!
