### ISSUE TITLE
Hyperparameter optimization for multivariate forecasting

### ISSUE THREAD

**Issue by masadshoaib** [Nixtla/neuralforecast#1119]
### Description

Hi,

I want to do hyperparameter optimization on my multivariate data. The default neuralforecast library allows one to declare   hist_exog_list=[]
  stat_exog_list=[]
  futr_exog_list=[]

for each model.

How can one do the same in the autoneuralforecast library?

Many thanks!

**Comment by marcopeix** [comment]
You can do something like this:

```python
config = dict(input_size=12, hist_exog_list=[], stat_exog_list=[], futr_exog_list=[])
model = AutoNHITS(h=12, config=config)
```
