### ISSUE TITLE
Do the models in the current library support multivariate forecasting?

### ISSUE THREAD

**Issue by YSAA1** [Nixtla/neuralforecast#1122]
### Description

For many tasks, there may be more than one label column to be predicted. Deep models can easily complete such tasks due to their high degree of freedom. However, I   check the documentation of the library and find that currently only supports multi-variable input models. It seems that multi-variable output models are not supported? 

### Use case

If I want to predict multiple variables at the same time, and furthermore, want to build a multi-output model that can classify or regress simultaneously, does the library support easy modification through callback functions or inherited subclasses to accomplish my expectations?

**Comment by elephaint** [comment]
From the docs:

[Forecasting capabilities](https://nixtlaverse.nixtla.io/neuralforecast/docs/capabilities/overview.html)
[Tutorial on multivariate forecasting](https://nixtlaverse.nixtla.io/neuralforecast/docs/tutorials/multivariate_tsmixer.html)
