### ISSUE TITLE
Distributed training of AutoNHITS on spark is very slow compared to local training

### ISSUE THREAD

**Issue by kiranklc** [Nixtla/neuralforecast#1142]
I am following the tutorial on distributed training here https://nixtlaverse.nixtla.io/neuralforecast/docs/tutorials/distributed_neuralforecast.html .

I am using a hdfs backend instead of S3. My data has 8000 unique ids and frequency is 5min. While training locally is completed within an hour, distributed training on spark and hdfs is taking more than 10 hours to complete.  On local machine, I have 16 cpu cores. The spark cluster has 3 worker nodes and 36 cores. I am not using GPUs.

My distributed configuration is:
dist_cfg = DistributedConfig(
    partitions_path=f'{hdfs_path_prefix}/partitions',  # path where the partitions will be saved
    num_nodes=3,  # number of nodes to use during training (machines)
    devices=1,   # number of GPUs in each machine
)
distributed_kwargs = dict(
    accelerator='cpu',
    enable_progress_bar=False,
    logger=False,
    enable_checkpointing=False,
)
def config(trial):
    return dict(
        input_size=624,
        max_steps=1400,
        learning_rate=trial.suggest_float('learning_rate', 1e-4, 1e-1, log=True),
        **distributed_kwargs
    )
nf = NeuralForecast(
    models=[
      AutoNHITS(h=24, config=config, backend='optuna', num_samples=2, alias='tuned_nhits'),
      ],
    freq=288,
)
nf.fit(spark_train, distributed_config=dist_cfg, val_size=312)

I have tried playing around with devices and num_nodes but there is no improvement in the time taken.
Kindly let me know what parameters to update to improve the training time.

**Comment by jmoralez** [comment]
Hey. If you're able to train locally you should do that, distributed training is only worth it when it's not possible to train in a single machine. Also that interface is designed for training with GPUs, by setting `devices=1` you're telling it to use 1 CPU per task, so there will be 3 tasks and each executor will only use one CPU. Also, if you set `devices=12` (CPUs per executor I guess) then you'll have 36 jobs where each one runs on one CPU, which will also be slow.
My suggestion is to either get a single machine (e.g. with 36 CPUs or 1 GPU) and run the training locally or use executors with GPUs for distributed training.

**Comment by kiranklc** [comment]
Hi. I am testing with just sample data, but the actual data is much larger. Thanks for the prompt response.

**Comment by jmoralez** [comment]
If the model fits in a single machine but the data doesn't you're probably better off using the approach described [here](https://nixtlaverse.nixtla.io/neuralforecast/docs/tutorials/large_datasets.html).

**Comment by kiranklc** [comment]
Thank you. It might work.
