### ISSUE TITLE
NeuralForecast: TFT support prediction for any start date without retraining

### ISSUE THREAD

**Issue by sophiag16** [Nixtla/neuralforecast#1147]
### Description

Add the option to input past data to the predict function. Similar to 'series' and 'past_covariates' in [darts TFT prediction](https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tft_model.html#darts.models.forecasting.tft_model.TFTModel.predict)

### Use case

After training the model using data till dt, and horizon=h, i would like to forecast for not just date range "dt+1 to dt+h+1" but for any date range i wish to get the prediction for (eg: from dt+h+1 to dt+2h+1).

**Comment by marcopeix** [comment]
Hello. This functionality already exists. Simply pass a `df` and `futr_df` argument to the `predict` method of the model. Our implementation of TFT supports both historical and future exogenous features as well. 

For the second part of your question, a model is trained to predict a sequence from an input sequence. Therefore, you can technically forecast any dates you want, but it will require an input sequence for the dates prior to that. So you must make predictions and use those predictions as input for the next set of predictions.

**Comment by sophiag16** [comment]
Thank you. Can you please also point me to the documentation which mentions this functionality? What I checked was the documentation for predict [here](https://nixtlaverse.nixtla.io/neuralforecast/models.tft.html#tft-predict). And that only mentioned a dataset input.
