### ISSUE TITLE
Getting Access to Slack Channel

### ISSUE THREAD

**Issue by Povinelli** [Nixtla/neuralforecast#1153]
When I click on the "Open" for "Ask a question or get support", it says to contact the Nixtla administrator. How do I get access to the slack channel?

Thanks in advance for the help.

**Comment by AzulGarza** [comment]
[slack channel](https://join.slack.com/t/nixtlacommunity/shared_invite/zt-1pmhan9j5-F54XR20edHk0UtYAPcW4KQ). :)

**Comment by Povinelli** [comment]
Greetings Azul,

I think I attended two of your talks at ISF. I liked the one where you used vim to interact with the TimeGPT API.

Anyway, I tried to login in with Google, but I get the following error message.

Thanks in advance for your help.

Best regards,
Richard

***@***.***

**Comment by tracykteal** [comment]
Thanks @Povinelli for the question, and we'd love to have your join our community Slack! Since there's login information involved, could you please email us at ops@nixtla.io and we can help you there.

**Comment by tracykteal** [comment]
Connected via email.
