### ISSUE TITLE
TFT model has no attribute "attention_weights"

### ISSUE THREAD

**Issue by joanna-baran-allegro** [Nixtla/neuralforecast#1156]
### Description

According to the docs I should be able to produce XAI plots with feature importance and attention weights after training TFT model. However, the documented attributes seems to not exist

### Link

https://nixtlaverse.nixtla.io/neuralforecast/models.tft.html#1-1-mean-attention

**Comment by jmoralez** [comment]
Hey. That was added in [1.7.5](https://github.com/Nixtla/neuralforecast/releases/tag/v1.7.5), are you using that version?
