### ISSUE TITLE
step_size in cross-validation

### ISSUE THREAD

**Issue by HAUNGTOFU** [Nixtla/neuralforecast#1161]
### Description

In this step(predicton = nf.cross_validation(df_end, val_size=val_size, test_size=test_size, n_windows=None,step_size=4)), I set `step_size = 4`, so is the `step_size` in the training process also 4?

**Comment by elephaint** [comment]
No, here `step_size` refers to the step size between each cross-validation window.

The step size between each window of temporal data used in the training process should be given to the initialization of the model.
