### ISSUE TITLE
[Core] PermissionDeniedError with TensorBoard Logging When Running NeuralForecast in Parallel

### ISSUE THREAD

**Issue by Yibei990826** [Nixtla/neuralforecast#1187]
### What happened + What you expected to happen

A user encountered a PermissionDeniedError with TensorBoard logging while running NeuralForecast in parallel using approximately 4000 unique_id and seven algorithms.

When she run a single unique_id, it completes successfully in about 6 minutes, but running in parallel (150 partitions, 144 GB memory, 72 cores) consistently results in TensorBoard-related permission issues, even though a custom NoOpLogger was used to disable logging. she is using a Pandas UDF in Databricks to run parallel forecasts across 150 partitions. The code runs successfully with a single unique_id, but fails in parallel.

The logging directory is writable, and she can create folders and files manually. However, TensorBoard still fails during parallel execution, indicating permission issues.

Example error message: `PermissionDeniedError: [Errno 13] Permission denied: '/Volumes/demand_dev/default/tem'`

### Versions / Dependencies

Databricks environment (144 GB memory, 72 cores)

### Reproduction script
```python
import os
import time
import pandas as pd
from neuralforecast.core import NeuralForecast
from neuralforecast.models import TimeMixer
from pytorch_lightning import Trainer
from pytorch_lightning.loggers import Logger

# Disable GPU and logging settings
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

# Custom No-Op Logger to effectively disable logging
class NoOpLogger(Logger):
    def log_metrics(self, metrics, step=None): pass
    def log_hyperparams(self, params): pass
    def save(self): pass

# Sample data
data = pd.DataFrame({
    'unique_id': ['series_1'] * 100,
    'ds': pd.date_range('2022-01-01', periods=100, freq='D'),
    'y': range(100)
})

# Forecasting function
def forecast_with_neuralforecast(train_df, horizon=10, freq='D'):
    model = TimeMixer(h=horizon)
    nf = NeuralForecast(models=[model], freq=freq)
    trainer = Trainer(logger=NoOpLogger(), enable_checkpointing=False, max_epochs=1000, default_root_dir='/path/to/tem')

    start_time = time.time()
    nf.fit(train_df, val_size=horizon)
    preds = nf.predict()
    elapsed_time = round(time.time() - start_time, 2)

    print(f"Run completed in {elapsed_time} seconds")
    return preds

# Run the script with a single series
forecast_with_neuralforecast(data)
```

### Issue Severity

None

**Comment by jmoralez** [comment]
The trainer arguments should go in the model, i.e. `model = TimeMixer(h=horizon, logger=False, enable_checkpointing=False)`

**Comment by Yibei990826** [comment]
This error seems to persist even after explicitly sets `logger=False and enable_checkpointing=False `within each model's initialization. Maybe something else is going wrong?
This is the code
```
import time
import pandas as pd
import numpy as np
import os
from pyspark.sql.functions import pandas_udf
from pyspark.sql.types import StructType, StructField, StringType, TimestampType, DoubleType
from neuralforecast.core import NeuralForecast
from neuralforecast.models import TimeMixer, SOFTS, TSMixer, PatchTST, iTransformer, NHITS, NBEATS
from pytorch_lightning import Trainer
import torch
from pytorch_lightning.loggers import Logger
# Set environment variables to force CPU-only mode and suppress GPU-related warnings
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Disable GPU visibility
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"  # Suppress TensorFlow logs
# Ensure PyTorch only uses CPU and restrict resources
torch.set_num_threads(1)  # Limit the number of CPU threads PyTorch can use
# Define a custom No-Op Logger to disable logging
class NoOpLogger(Logger):
    @property
    def name(self):
        return "NoOpLogger"
    @property
    def version(self):
        return "0"
    def log_metrics(self, metrics, step):
        pass
    def log_hyperparams(self, params):
        pass
    def save(self):
        pass
# Define the forecasting function with logging and checkpointing disabled
def forecast_with_neuralforecast(train_df, horizon=15, freq='W-MON'):
    train_df['ds'] = [pd.to](http://pd.to/)_datetime(train_df['ds'])
    train_df = train_df.set_index('ds').reset_index()
    n_series = 1
    timemixer_model = TimeMixer(input_size=2 * horizon, h=horizon, n_series=n_series, scaler_type='identity', early_stop_patience_steps=3)
    softs_models = SOFTS(h=horizon, input_size=2 * horizon, n_series=n_series, max_steps=1000, early_stop_patience_steps=3, logger=False, enable_checkpointing=False)
    tsmixer_models = TSMixer(h=horizon, input_size=2 * horizon, n_series=n_series, max_steps=1000, early_stop_patience_steps=3,  logger=False, enable_checkpointing=False)
    nbeats_model = NBEATS(input_size=2 * horizon, h=horizon, scaler_type='identity', max_steps=1000, early_stop_patience_steps=3,  logger=False, enable_checkpointing=False)
    nhits_model = NHITS(input_size=2 * horizon, h=horizon, scaler_type='identity', max_steps=1000, early_stop_patience_steps=3,  logger=False, enable_checkpointing=False)
    patchtst_model = PatchTST(input_size=2 * horizon, h=horizon, encoder_layers=3, n_heads=4, hidden_size=16, dropout=0.3, patch_len=16, stride=8, scaler_type='identity', max_steps=1000, early_stop_patience_steps=5, logger=False, enable_checkpointing=False)
    iTransformer_model = iTransformer(input_size=2 * horizon, h=horizon, n_series=n_series, e_layers=2, hidden_size=128, d_ff=128, scaler_type='identity', max_steps=1000, early_stop_patience_steps=3,  logger=False, enable_checkpointing=False)
    models = [timemixer_model, softs_models, tsmixer_models, nbeats_model, nhits_model, patchtst_model, iTransformer_model]
    model_names = ['TimeMixer', 'SOFTS', 'TSMixer', 'NBEATS', 'NHITS', 'PatchTST', 'iTransformer']
    forecast_dfs = []
    run_times = []
    for i, model in enumerate(models):
        nf = NeuralForecast(models=[model], freq=freq)
        # Trainer with the custom No-Op Logger and checkpointing disabled
        trainer = Trainer(
            max_epochs=1000,
            logger=NoOpLogger(),  # Use custom No-Op Logger
            enable_checkpointing=False,  # Disable checkpointing
            enable_progress_bar=False,  # Disable progress bar
            default_root_dir='/tmp/',  # Use a writable directory for temp files
            log_every_n_steps=1000  # Set high logging frequency to minimize log attempts
        )
        start = time.time()
        nf.fit(train_df, val_size=horizon)
        preds = nf.predict()
        # Calculate run time
        end = time.time()
        elapsed_time = round(end - start, 0)
        run_times.append({'unique_id': train_df['unique_id'].iloc[0], 'Model': model_names[i], 'RunTime': elapsed_time})
        preds = preds.reset_index()
        preds = preds.rename(columns={'yhat': model_names[i]})
        forecast_dfs.append(preds[['unique_id', 'ds', model_names[i]]])
    # Merge forecasts into one DataFrame
    merged_forecast = forecast_dfs[0]
    for forecast_df in forecast_dfs[1:]:
        merged_forecast = pd.merge(merged_forecast, forecast_df, on=['unique_id', 'ds'], how='left')
    run_times_df = pd.DataFrame(run_times)
    return merged_forecast, run_times_df
# Define schemas
prediction_schema = StructType([
    StructField("unique_id", StringType()),
    StructField("ds", TimestampType()),
    StructField("TimeMixer", DoubleType()),
    StructField("SOFTS", DoubleType()),
    StructField("TSMixer", DoubleType()),
    StructField("NBEATS", DoubleType()),
    StructField("NHITS", DoubleType()),
    StructField("PatchTST", DoubleType()),
    StructField("iTransformer", DoubleType())
])
runtime_schema = StructType([
    StructField("unique_id", StringType()),
    StructField("Model", StringType()),
    StructField("RunTime", DoubleType())
])
# Adjusted Pandas UDF for predictions
def forecast_prediction_udf(pdf):
    forecast, _ = forecast_with_neuralforecast(pdf)
    return forecast
# Adjusted Pandas UDF for runtimes
def forecast_runtime_udf(pdf):
    _, runtime_df = forecast_with_neuralforecast(pdf)
    return runtime_df
# Assuming spark is your SparkSession variable and ai_input_q1000_pd_origin is your original Pandas DataFrame
ai_input_q1000_spark_df = spark.createDataFrame(ai_input_q1000_pd_origin)
# Repartition by 'unique_ID' into 150 partitions for better parallelism
num_partitions = 150
partitioned_df = ai_input_q1000_spark_df.repartition(num_partitions, "unique_id")
# Apply the prediction UDF in parallel on the repartitioned dataframe
forecast_prediction_df = partitioned_df.groupBy("unique_id").applyInPandas(forecast_prediction_udf, schema=prediction_schema)
# Apply the runtime UDF in parallel on the repartitioned dataframe
forecast_runtime_df = partitioned_df.groupBy("unique_id").applyInPandas(forecast_runtime_udf, schema=runtime_schema)
# Write the PySpark DataFrame to Delta Table with schema evolution enabled for predictions
forecast_prediction_df.write.format("delta") \
    .mode("overwrite") \
    .option("mergeSchema", "true") \
    .saveAsTable("demand_dev.forecast.neuralforecast_predictions")
# Write the PySpark DataFrame to Delta Table with schema evolution enabled for runtimes
forecast_runtime_df.write.format("delta") \
    .mode("overwrite") \
    .option("mergeSchema", "true") \
    .saveAsTable("demand_dev.forecast.neuralforecast_runtime")
```

**Comment by jmoralez** [comment]
The timemixer doesn't have those arguments set:

> TimeMixer(input_size=2 * horizon, h=horizon, n_series=n_series, scaler_type='identity', early_stop_patience_steps=3)

That should be `TimeMixer(input_size=2 * horizon, h=horizon, n_series=n_series, scaler_type='identity', early_stop_patience_steps=3, logger=False, enable_checkpointing=False)`

Also note that the `trainer` isn't used anywhere in the provided code, that shouldn't be there as it serves no purpose. All those arguments should go inside each of the models, so my suggestion would be to place them in a common dict like `trainer_kwargs` and provide that to every model, like `TimeMixer(input_size=2 * horizon, h=horizon, n_series=n_series, scaler_type='identity', early_stop_patience_steps=3, **trainer_kwargs)`

**Comment by leirhyh** [comment]
I tried add **trainer_kwargs,  I got this issues solved but I got another issues. I have around 4000 unique_id data set, some of them have many zeros, (some maybe > 80%)--no sales. I try to run only one model to manager memory alllocation easier.  I got issues as follow: import time
import pandas as pd
import numpy as np
import os
from pyspark.sql.functions import pandas_udf
from pyspark.sql.types import StructType, StructField, StringType, TimestampType, DoubleType
from neuralforecast.core import NeuralForecast
from neuralforecast.models import TimeMixer, SOFTS, TSMixer, PatchTST, iTransformer, NHITS, NBEATS
from pytorch_lightning import Trainer
import torch
import psutil
import logging

# Set environment variables to force CPU-only mode and suppress GPU-related warnings
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Disable GPU visibility
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"  # Suppress TensorFlow logs

# Ensure PyTorch only uses CPU and restrict resources
torch.set_num_threads(4)  # Limit the number of CPU threads PyTorch can use

# Set up logging to monitor memory usage
logging.basicConfig(level=logging.INFO)

# Define common arguments in a dictionary
trainer_kwargs = {
    'logger': False,
    'enable_checkpointing': False,
    'batch_size': 32,  # Adjust this based on your memory constraints
}

# Log memory usage
def log_memory_usage():
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    logging.info(f"Memory Usage: {mem_info.rss / 1024 ** 3:.2f} GB")

# Function to filter datasets based on zero proportion threshold
def filter_zero_heavy_datasets(df, zero_threshold=0.95):
    """
    Filters out datasets where the proportion of zero values exceeds the threshold.
    
    Parameters:
        df (pd.DataFrame): Input DataFrame with time series data.
        zero_threshold (float): The percentage threshold for zeros (0.95 means 95%).

    Returns:
        bool: Returns True if the dataset is acceptable, False otherwise.
    """
    non_zero_count = (df['y'] != 0).sum()  # Count of non-zero values
    total_count = df['y'].count()          # Total number of values

    # Calculate the proportion of zeros and filter based on threshold
    return non_zero_count / total_count >= (1 - zero_threshold)

# Function to run each model individually
def forecast_with_individual_model(train_df, model, model_name, horizon=15, freq='W-MON'):
    train_df['ds'] = pd.to_datetime(train_df['ds'])
    train_df = train_df.set_index('ds').reset_index()
    n_series = 1
    
    nf = NeuralForecast(models=[model], freq=freq)

    # Time the run
    start = time.time()
    nf.fit(train_df, val_size=horizon)
    preds = nf.predict()
    end = time.time()
    
    # Capture the run time and predictions
    elapsed_time = round(end - start, 0)
    run_time = {'unique_id': train_df['unique_id'].iloc[0], 'Model': model_name, 'RunTime': elapsed_time}
    
    preds = preds.reset_index()
    preds = preds.rename(columns={'yhat': model_name})
    
    return preds[['unique_id', 'ds', model_name]], run_time

# Run models sequentially after filtering the data
def run_models_on_filtered_data(train_df, zero_threshold=0.95):
    """
    Filters the data and runs models on the filtered datasets.
    
    Parameters:
        train_df (pd.DataFrame): Input DataFrame with time series data for multiple unique IDs.
        zero_threshold (float): Threshold for filtering datasets based on the proportion of zero values.
    
    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]: Merged forecasts and runtimes DataFrames.
    """
    # Apply the filter per group, then concatenate the filtered groups
    filtered_train_df = train_df.groupby('unique_id').filter(lambda df: filter_zero_heavy_datasets(df, zero_threshold=zero_threshold))

    input_size = 10  # Ensure this is consistent with the time steps or features in your dataset

    models = [
        (TimeMixer(input_size=input_size, h=15, n_series=1, scaler_type='identity', early_stop_patience_steps=3, **trainer_kwargs), 'TimeMixer'),
        (SOFTS(h=15, input_size=input_size, n_series=1, max_steps=1000, early_stop_patience_steps=3, **trainer_kwargs), 'SOFTS'),
        (TSMixer(h=15, input_size=input_size, n_series=1, max_steps=1000, early_stop_patience_steps=3, **trainer_kwargs), 'TSMixer'),
        (NBEATS(input_size=input_size, h=15, scaler_type='identity', max_steps=1000, early_stop_patience_steps=3, **trainer_kwargs), 'NBEATS'),
        (NHITS(input_size=input_size, h=15, scaler_type='identity', max_steps=1000, early_stop_patience_steps=3, **trainer_kwargs), 'NHITS'),
        (PatchTST(input_size=input_size, h=15, encoder_layers=2, n_heads=2, hidden_size=16, dropout=0.3, patch_len=8, stride=4, scaler_type='identity', max_steps=1000, early_stop_patience_steps=5, **trainer_kwargs), 'PatchTST'),
        (iTransformer(input_size=input_size, h=15, n_series=1, e_layers=2, hidden_size=128, d_ff=128, scaler_type='identity', max_steps=1000, early_stop_patience_steps=3, **trainer_kwargs), 'iTransformer')
    ]

    forecast_dfs = []
    run_times = []

    for model, model_name in models:
        logging.info(f"Running model: {model_name}")
        preds, run_time = forecast_with_individual_model(filtered_train_df, model, model_name)
        forecast_dfs.append(preds)
        run_times.append(run_time)

    # Merge the predictions and run times into DataFrames
    merged_forecast = forecast_dfs[0]
    for forecast_df in forecast_dfs[1:]:
        merged_forecast = pd.merge(merged_forecast, forecast_df, on=['unique_id', 'ds'], how='left')

    run_times_df = pd.DataFrame(run_times)
    
    return merged_forecast, run_times_df

# Define schemas
prediction_schema = StructType([
    StructField("unique_id", StringType()),
    StructField("ds", TimestampType()),
    StructField("TimeMixer", DoubleType()),
    StructField("SOFTS", DoubleType()),
    StructField("TSMixer", DoubleType()),
    StructField("NBEATS", DoubleType()),
    StructField("NHITS", DoubleType()),
    StructField("PatchTST", DoubleType()),
    StructField("iTransformer", DoubleType())
])

runtime_schema = StructType([
    StructField("unique_id", StringType()),
    StructField("Model", StringType()),
    StructField("RunTime", DoubleType())
])

# Adjusted Pandas UDF for predictions
def forecast_prediction_udf(pdf):
    forecast, _ = run_models_on_filtered_data(pdf, zero_threshold=0.95)
    return forecast

# Adjusted Pandas UDF for runtimes
def forecast_runtime_udf(pdf):
    _, runtime_df = run_models_on_filtered_data(pdf, zero_threshold=0.95)
    return runtime_df

# Assuming spark is your SparkSession variable and ai_input_q1000_pd_origin is your original Pandas DataFrame
ai_input_q1000_spark_df = spark.createDataFrame(ai_input_q1000_pd_origin)

# Calculate the number of partitions dynamically based on the number of cores and unique IDs
num_partitions = min(4 * 72, 4000 // 20)  # This results in 200 partitions based on 72 cores and 4000 unique IDs

# Repartition by 'unique_ID' into the calculated number of partitions for better parallelism
partitioned_df = ai_input_q1000_spark_df.repartition(num_partitions, "unique_id")

# Apply the prediction UDF in parallel on the repartitioned dataframe
forecast_prediction_df = partitioned_df.groupBy("unique_id").applyInPandas(forecast_prediction_udf, schema=prediction_schema)

# Apply the runtime UDF in parallel on the repartitioned dataframe
forecast_runtime_df = partitioned_df.groupBy("unique_id").applyInPandas(forecast_runtime_udf, schema=runtime_schema)

# Write the PySpark DataFrame to Delta Table with schema evolution enabled for predictions
forecast_prediction_df.write.format("delta") \
    .mode("overwrite") \
    .option("mergeSchema", "true") \
    .saveAsTable("demand_dev.forecast.neuralforecast_predictions")

# Write the PySpark DataFrame to Delta Table with schema evolution enabled for runtimes
forecast_runtime_df.write.format("delta") \
    .mode("overwrite") \
    .option("mergeSchema", "true") \
    .saveAsTable("demand_dev.forecast.neuralforecast_runtime")


PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/root/.ipykernel/3527/command-3902966023841368-773337968", line 144, in forecast_prediction_udf
  File "/root/.ipykernel/3527/command-3902966023841368-773337968", line 110, in run_models_on_filtered_data
  File "/root/.ipykernel/3527/command-3902966023841368-773337968", line 65, in forecast_with_individual_model
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-f42a21ef-2d4c-43ce-8509-18b8b5c13a8a/lib/python3.11/site-packages/neuralforecast/core.py", line 486, in fit
    self.dataset, self.uids, self.last_dates, self.ds = self._prepare_fit(
                                                        ^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-f42a21ef-2d4c-43ce-8509-18b8b5c13a8a/lib/python3.11/site-packages/neuralforecast/core.py", line 304, in _prepare_fit
    dataset, uids, last_dates, ds = TimeSeriesDataset.from_df(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-f42a21ef-2d4c-43ce-8509-18b8b5c13a8a/lib/python3.11/site-packages/neuralforecast/tsdataset.py", line 367, in from_df
    max_size = max(sizes)
               ^^^^^^^^^^
ValueError: max() arg is an empty sequence
File <command-3902966023841368>, line 171
    165 forecast_runtime_df = partitioned_df.groupBy("unique_id").applyInPandas(forecast_runtime_udf, schema=runtime_schema)
    167 # Write the PySpark DataFrame to Delta Table with schema evolution enabled for predictions
    168 forecast_prediction_df.write.format("delta") \
    169     .mode("overwrite") \
    170     .option("mergeSchema", "true") \
--> 171     .saveAsTable("demand_dev.forecast.neuralforecast_predictions")
    173 # Write the PySpark DataFrame to Delta Table with schema evolution enabled for runtimes
    174 forecast_runtime_df.write.format("delta") \
    175     .mode("overwrite") \
    176     .option("mergeSchema", "true") \
    177     .saveAsTable("demand_dev.forecast.neuralforecast_runtime")
File /databricks/spark/python/pyspark/errors/exceptions/captured.py:261, in capture_sql_exception.<locals>.deco(*a, **kw)
    257 converted = convert_exception(e.java_exception)
    258 if not isinstance(converted, UnknownException):
    259     # Hide where the exception came from that shows a non-Pythonic
    260     # JVM exception message.
--> 261     raise converted from None
    262 else:
    263     raise


Could you help me fix this issues?  Thanks

**Comment by leirhyh** [comment]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x2 and 3x5)
File <command-375622246388227>, line 146
    143 time_mixer_model = TimeMixer(input_size=input_size, h=horizon, n_series=1, scaler_type='identity', early_stop_patience_steps=3, **trainer_kwargs)
    145 # Run TimeMixer model and save predictions and runtime
--> 146 apply_model_and_save(ai_input_q1000_spark_df, time_mixer_model, "TimeMixer", input_size, horizon)
    148 # Define another model and run
    149 softs_model = SOFTS(h=horizon, input_size=input_size, n_series=1, max_steps=1000, early_stop_patience_steps=3, **trainer_kwargs)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/torch/nn/modules/linear.py:125, in Linear.forward(self, input)
    124 def forward(self, input: Tensor) -> Tensor:
--> 125     return F.linear(input, self.weight, self.bias)
