### ISSUE TITLE
Chore: deprecate NIXTLA_ID_AS_COL or issue warning

### ISSUE THREAD

**Issue by elephaint** [Nixtla/neuralforecast#1234]
### What happened + What you expected to happen

We need to make NIXTLA_ID_AS_COL the default behavior or start showing deprecation messages, as the default behavior of NF is now inconsistent with the API of our other libs (SF, MF, HF).

### Versions / Dependencies

1.7.7

### Reproduction script

n/a

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
This is what is done in #1220
