### ISSUE TITLE
.yml environment channels

### ISSUE THREAD

**Issue by alejandroxag** [Nixtla/neuralforecast#131]
Pytorch and pytorch lightning downloads take a lot of time depending on the download channel, and some HTTP issues arise:

1. Pytorch: CondaHTTPError: HTTP 000 CONNECTION FAILED for URL <https://conda.anaconda.org/pytorch/linux-64/pytorch-1.10.2-py3.7_cuda11.3_cudnn8.2.0_0.tar.bz2>
2. Pytorch lightning: socket.timeout: The read operation timed out

In the case of pytorch, specifying the channel (-pytorch::pytorch, -pytorch::torchvision, etc.) solved the problem; with pytorch lightning, setting the timeout to a large number (pip install -U --timeout 2000 pytorch-lightning) did the trick.

**Comment by FedericoGarza** [comment]
Hi, what command are you training to run? The file [environment.yml](https://github.com/Nixtla/neuralforecast/blob/main/environment.yml) already has the channels.
