### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by vglaucus** [Nixtla/neuralforecast#168]
Due PyTorch being a requirement, I had to downgrade out of python3.10 somehow, so I tried with conda

I tried this to no avail: 
```
conda create -n nixtla python=3.7  # And also 3.6
conda activate nixtla
conda install -c nixtla neuralforecast
```
getting library errors such as:
```Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

I finally was able to install it after using python=3.7.11 as shown in the documentation (not generic 3.7 as shown above)

**Comment by mergenthaler** [comment]
@all-contributors please add @vglaucus  for bug
