### ISSUE TITLE
Test for batch construction fails on Windows

### ISSUE THREAD

**Issue by Pedja94** [Nixtla/neuralforecast#178]
When running test function test_batch_construction_windows in data__tsdataset.ipynb notebook folowing error appears.
![Screenshot 2022-02-09 223255](https://user-images.githubusercontent.com/13970154/153293762-5548b81f-90ba-4ac6-91e2-2a6fcf388894.png)

I'm using python enviroment in anaconda3 on Windows.

**Comment by kdgutier** [comment]
Are you using CPU or GPU for your work?

**Comment by Pedja94** [comment]
I'm using GPU.

**Comment by kdgutier** [comment]
You need to move the memory from GPU to cpu then to NumPy.
Hope it helps
https://discuss.pytorch.org/t/what-is-the-cpu-in-pytorch/15007

**Comment by kdgutier** [comment]
Also, these tests are meant for the sanity checks of the library. 
You might not need them for your purposes.
