### ISSUE TITLE
hyperopt error: 'test_y_true' not found

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/neuralforecast#181]
I'm getting this error trying to run ` nf.experiments.utils.hyperopt_tunning`.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/10517170/153336809-39506633-d36a-4213-beb5-ccd68b32ab8b.png">

**Comment by FedericoGarza** [comment]
The issue arises due to a strange interaction between `ds_in_test` and `return_forecasts`: if `ds_in_test` is 0 then the function `nf.experiments.utils.model_fit_predict` does not store `'test_y_true'`, 

https://github.com/Nixtla/neuralforecast/blob/09ce6d0075bbf287d78483d04f107dec7505fc5c/neuralforecast/experiments/utils.py#L532-L542

But if `return_forecasts` is True then the function `nf.experiments.utils.evaluate_model` tries to get `'test_y_true'` from the `results` output of the `nf.experiments.utils.model_fit_predict` function:

https://github.com/Nixtla/neuralforecast/blob/09ce6d0075bbf287d78483d04f107dec7505fc5c/neuralforecast/experiments/utils.py#L596-L603

**Comment by FedericoGarza** [comment]
The easiest solution:

```
if return_forecasts and ds_in_test > 0: 
     forecasts_test = {} 
     test_values = (('test_y_true', results['test_y_true']), ('test_y_hat', results['test_y_hat']), 
                     ('test_mask', results['test_mask']), ('test_meta_data', results['test_meta_data'])) 
     forecasts_test.update(test_values) 
     results_output['forecasts_test'] = forecasts_test 
  
 return results_output 
```

**Comment by cchallu** [comment]
solved, it will only return forecasts if ds_in_test > 0
