### ISSUE TITLE
hyperopt error: save progress failed

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/neuralforecast#182]
After a couple of hyperopt runs I realized that `nf.experiments.utils.hyperopt_tunning` wasn't saving my trials, due to these lines:

https://github.com/Nixtla/neuralforecast/blob/09ce6d0075bbf287d78483d04f107dec7505fc5c/neuralforecast/experiments/utils.py#L554-L556

I think 5 shouldn't be hardcoded. Maybe we can add a  `step_save_progress`  argument and default it to 5.

**Comment by FedericoGarza** [comment]
@cchallu what do you think?

**Comment by cchallu** [comment]
sounds good, I will add the parameter.
