### ISSUE TITLE
Error running nbdev_build_docs

### ISSUE THREAD

**Issue by juniors90** [Nixtla/neuralforecast#196]
I have tried to compile the documentation following the workflow outlined in [CONTRIBUTING.md](https://github.com/Nixtla/neuralforecast/blob/main/CONTRIBUTING.md).

The truth is that I get an error when generating the documentation using the latest version of `nbdev==1.2.2`.

**Solution**:

To compile without errors it is necessary to use `nbdev==1.1.23`.

**Comment by kdgutier** [comment]
Thanks for catching that, are the nbdev dependencies set to nbdev 1.1.23?
Do we need to change it in the requirements?

**Comment by FedericoGarza** [comment]
Yes, we need to set the `nbdev` dependency to `1.1.23`. The compilation problem is related to https://github.com/fastai/nbdev/issues/595, it seems there is a problem with the new `nbdev` version using `@dataclass`. I'm labeling this as `good first issue`.
