### ISSUE TITLE
Add `neuralforecast` to conda-forge channel

### ISSUE THREAD

**Issue by sugatoray** [Nixtla/neuralforecast#203]
It will be nice to have `neuralforecast` on conda-forge channel. This will allow users to easily download the library using conda and also, any downstream library, which uses `neuralforecast` as a dependency, will be able to add itself on conda-forge in future conveniently.

I have already submitted a PR on conda-forge. The PR was just merged.

- https://github.com/conda-forge/staged-recipes/pull/18423

Give it 2-3 hours to find `neuralforecast` on conda-forge.

Install with:

```sh
conda install -c conda-forge neuralforecast
```

**Comment by sugatoray** [comment]
cc: @FedericoGarza

**Comment by sugatoray** [comment]
It is available now.

**Comment by FedericoGarza** [comment]
Awesome @sugatoray! Thank you!🙌
