### ISSUE TITLE
Can model.forecast support batch of windows rather than just one?

### ISSUE THREAD

**Issue by mistycheney** [Nixtla/neuralforecast#210]
**Is your feature request related to a problem? Please describe.**

Is there a version of `model.forecast` that takes a batch of windows rather than just one window? Take NBEATS for example - maybe also applies to other models. Currently `model.forecast` only supports inputting one window and returning the forecast for that window. This is inefficient for testing on a long test time series with a large number of windows. The implementation right now does not allow using larger batches to fully utilize GPU.

**Describe the solution you'd like**

I would like the implementation of `model.forecast` be extended to support cases when the input contains multiple windows and the returned results are the forecast for each of the input windows.

**Comment by kdgutier** [comment]
Hi @mistycheney, thanks for the comment. 

We believe that the NBEATS.forecast method allows to define a batch_size. 
Here is method's (source code)[https://github.com/Nixtla/neuralforecast/blob/main/neuralforecast/models/nbeats/nbeats.py#L734-#L783].

Would you be able to better point us to your finding?

**Comment by mistycheney** [comment]
Thanks. These are very helpful. I did not find these even though I have played around this library for a whole week, so ended up writing something similar to these myself. Would love it if these can be placed at a more eye-catching location of README and document page. Great library! Thanks.

**Comment by kdgutier** [comment]
Thanks for the suggestion, 
We have been thinking some time to include the prediction as a method for the classes.
We are yet to think a general class to do it, and avoiding the code duplication across models.
