### ISSUE TITLE
N-HiTS  vs Temporal Fusion Transformer

### ISSUE THREAD

**Issue by esbraun** [Nixtla/neuralforecast#240]
The N-HiTS arxiv article did not include a performance comparison with Google's popular Temporal Fusion Transformer (https://arxiv.org/abs/1912.09363). Is anyone aware of a head-to-head that's been published or otherwise shared online? Thanks!

**Comment by esbraun** [comment]
I greatly appreciate the prompt response! Your point about long horizon forecasts is well taken. Perhaps I should have phrased my question differently. I generally deal with forecasting problems with rich exogenous features and a "medium term" horizon (e.x. a daily forecast with a 28-day horizon). My hope is to understand better understand what advantages N-HiTS may offer in this situation compared to TFT, which I've found to be performant in the past. I'll do some empirical investigations of my own.

Thank you for the excellent open-sourced forecasting ecosystem you're developing. It's an invaluable contribution to the data science community.

**Comment by kdgutier** [comment]
It is a very nice research direction, 
- TFT just like N-HiTS has MLP based decoders for the direct multi-step forecasting strategy.
- The hierarchical interpolation strategy should be able to be implemented in the decoder.
- For more inspiration hierarchical interpolation strategy has some connection the the agnostic and specific contexts in the  [MQForecaster](https://arxiv.org/abs/1711.11053) architecture too.
