### ISSUE TITLE
Question about nhits/nbeats

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [Nixtla/neuralforecast#245]
I'm trying to understand if a forecast model can be used without refitting, just like an ML model. Say for instance I trained a model that takes [1,2,3] as input and predicts 4. Can I feed into a new sequence into this model [2,3,4] and it gives me 5? I tried it and it works, but is this recommended or do I need to re-fit the model specifically for the new sequence [2,3,4] for maximal accuracy?

**Comment by cchallu** [comment]
Hi @Karlheinzniebuhr. Yes, forecasting models such as the N-HiTS can be used without re-training every time you have new data and want to make a forecast. However, depending on the use case, it is best to re-train the model often (ie. once a day, week, month, etc.) to account for potential distribution shifts.
