### ISSUE TITLE
N-HiTS/N-BEATS Decomposition Components

### ISSUE THREAD

**Issue by eddietaylor** [Nixtla/neuralforecast#264]
**Is your feature request related to a problem? Please describe.**
We are currently working on a problem where we need to extract the seasonality component of our forecast. With prophet we can do this but it is not clear that this can be done with the neuralforecast models.

**Describe the solution you'd like**
It would be great to have a method like the *components methods in the prophet model class.

**Describe alternatives you've considered**
We've simply considered sticking with our prophet model but would prefer to try the neuralforecast models!

**Additional context**
n/a

**Comment by eddietaylor** [comment]
@Cy-Ke

**Comment by cchallu** [comment]
Hello @eddietaylor, thanks for your interest in the library. We have an example of decomposition components in https://github.com/Nixtla/neuralforecast/blob/main/nbs/models.nhits.ipynb.

**Comment by eddietaylor** [comment]
Thank you so much!
