### ISSUE TITLE
[Question] Should I worry about my N-HiTS forecast methodology?

### ISSUE THREAD

**Issue by gsamaras** [Nixtla/neuralforecast#265]
I want to perform an univariate 3-1 Time Series Forecasting, i.e. feed the model with an input of 3 samples and the model to predict the next sample (so horizon is 1).

I have adapted [nhits__example.ipynb](https://colab.research.google.com/drive/1WjBbQzaivQhOldGolzymOtLmo6QX4Ieg#scrollTo=z9YUtuhNdsBA) to my data and all seem fine. I want now to use [forecast()](https://github.com/Nixtla/neuralforecast/blob/main/neuralforecast/models/nhits/nhits.py#L725), since in my application, 3 numbers will arrive as input, and the model should forecast a single number. Here is an example where I am using the 3 last samples before the last one of my data, as input data for the forecast method:
```
n_time_in = 3
n_time_out = 1

model = nf.auto.NHITS(horizon=n_time_out)
model.space['frequency'] = "min"
model.space['n_time_in'] = n_time_in

model.fit(Y_df=Y_df,  ...)

Y_df.iloc[[-4, -3, -2, -1]]
### prints
	                      ds	y	unique_id
8611	2020-05-19 11:29:29.504	1020.8758	dummy
8612	2020-05-19 11:30:30.544	1020.8758	dummy
8613	2020-05-19 11:31:31.724	1059.2924	dummy
8614	2020-05-19 11:32:32.780	1025.6858	dummy
###

results = model.forecast(Y_df=Y_df.iloc[[-4, -3, -2]]) # groundtruth: 1025.6858
print(results)
```
which prints:
```
..
  unique_id                      ds            y
0     dummy 2020-05-20 11:31:31.724  1060.287842
```

I am wondering if there is a problem in my methodology, because the forecast's datetime is for next day and not next minute, despite the fact that I have set frequency to `min` (minutes). Am I missing something? Or my methodology is OK and I can ignore this next day forecast and interpret it like the next minute forecast?

**Comment by cchallu** [comment]
Hi @gsamaras, we launched a new version of NeuralForecast to make usage easier, including the forecast methods. Let us know if you have questions regarding the new version.
