### ISSUE TITLE
How to increase Dataloader's workers?

### ISSUE THREAD

**Issue by gsamaras** [Nixtla/neuralforecast#266]
I am using [nhits__example.ipynb](https://colab.research.google.com/drive/1WjBbQzaivQhOldGolzymOtLmo6QX4Ieg#scrollTo=z9YUtuhNdsBA) with my data and CPU. All seem fine, but during training I get:

```
/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:245: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 4 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
```
How can I do that please? Passing `num_workers` to `fit()` won't work of course.

If I use a GPU, the warning disappears.

**Comment by kdgutier** [comment]
For the moment the Windows dataloader is creating rolling windows using the GPU, we need to move this operation into the models to be able to parallelize the workers in future releases.

The parallelization speed gains of increasing the cores are dwarfed versus the unfold GPU operation.
