### ISSUE TITLE
[Question] How to save my trained model?

### ISSUE THREAD

**Issue by gsamaras** [Nixtla/neuralforecast#268]
For example, in [nhits__example.ipynb](https://colab.research.google.com/drive/1WjBbQzaivQhOldGolzymOtLmo6QX4Ieg#scrollTo=z9YUtuhNdsBA), an N-HiTS model is trained. How I can save it and use it afterwards? Can't find a `save()` in [nhits.py](https://github.com/Nixtla/neuralforecast/blob/main/neuralforecast/models/nhits/nhits.py).

**Comment by mergenthaler** [comment]
Hi @gsamaras, thanks for using neuralforecast. Our model classes, including the N-HiTS, are Pytorch Lightning modules (`pl.LightningModule`), so you can use pl's `save` and `load` functions. 

We suggest using the trainer's `save_checkpoint` method to save models, and the `load_from_checkpoint` method on the model class to load weights and hyperparameters. 

You can find an example in https://colab.research.google.com/drive/1uFCO2UBpH-5l2fk3KmxfU0oupsOC6v2n.

**Comment by gsamaras** [comment]
Hey @mergenthaler thanks for the answer, but I am finding myself unable to save the model for now. As I had followed the example notebook that I shared before, my code is this:

```
import neuralforecast as nf

model = nf.auto.NHITS(horizon=1)
model.space["max_steps"] = hp.choice("max_steps", [1000])

model.fit(
    Y_df=Y_df,
    X_df=None,  # Exogenous variables
    S_df=None,  # Static variables
    hyperopt_steps=5,  # Using 5 hyperopt steps
    n_ts_val=n_ts_val,  
    n_ts_test=n_ts_test,  
    results_dir="./results/autonhits",
    save_trials=True,
    loss_function_val=nf.losses.numpy.mape,  
    loss_functions_test={
        "mape": nf.losses.numpy.mape,
    },
    return_test_forecast=True,
    verbose=False,
)
model.model.save_checkpoint("example.ckpt") # model. and model.model.model also fail
```
which fails with:
```
AttributeError: 'NHITS' object has no attribute 'save_checkpoint'
```
Is there a way to save the model the way I have written my code now? Or I need to rewrite it with explicitly using a PL Trainer?
