### ISSUE TITLE
[Enhancement] Include ES-RNN space in auto.py

### ISSUE THREAD

**Issue by gsamaras** [Nixtla/neuralforecast#269]
If I am not mistaken, ES-RNN is not included in [auto.py](https://github.com/Nixtla/neuralforecast/blob/main/neuralforecast/auto.py), so a non-ML expert cannot simply use it like N-HiTS in this [example](https://colab.research.google.com/drive/1WjBbQzaivQhOldGolzymOtLmo6QX4Ieg#scrollTo=J_XLz8_z9mBU).

IMHO, it would be nice to have it there, so that ES-RNN enjoys the same automations as RNN, NBEATS, N-HiTS & MQN-HiTS.

**Comment by cchallu** [comment]
Hi @gsamaras, we lunched a new version of NeuralForcast with an easier interface. We will include ES-RNN in the following weeks.
