### ISSUE TITLE
[Bug] progress_bar_refresh_rate causes error with pytorch-lightning>=1.7

### ISSUE THREAD

**Issue by chillerobscuro** [Nixtla/neuralforecast#277]
For a new user installing neuralforecast and all dependencies, they will hit an error when calling `model.forecast()` when building a model or even just following an example step for step (ie the [mqnhits example](https://github.com/Nixtla/neuralforecast/blob/main/examples/mqnhits.ipynb))

The error is: `TypeError: init() got an unexpected keyword argument ‘progress_bar_refresh_rate’`

From the [pytorch-lightning docs](https://pytorch-lightning.readthedocs.io/en/1.6.5/common/trainer.html): "progress_bar_refresh_rate has been deprecated in v1.5 and will be removed in v1.7. Please pass TQDMProgressBar with refresh_rate directly to the Trainer’s callbacks argument instead."

Seems like `progress_bar_refresh_rate` is passed to many `pl.Trainer` objects in this repo - I think it'd make sense to remove those so that the newest version of `pytorch-lightning` is still valid, and I'm not sure it would hurt performance in any way.

Alternatively, limit the lightning version to <1.7.

Either way, should solve the issue. I am really enjoying this library, thanks for all the good work.

**Comment by Jason7even** [comment]
I met the same problem and solved it by `pip uninstall pytorch-lightning` and `pip install pytorch-lightning==1.6`.
Thanks for @chillerobscuro.
And this library helps me a lot, thanks for Nixtla/neuralforecast and its contributors.

**Comment by Jason7even** [comment]
您好，我已经收到您的邮件，祝生活愉快。
