### ISSUE TITLE
Installation error for neuralforecast

### ISSUE THREAD

**Issue by Msaleh87** [Nixtla/neuralforecast#280]
I used the following command to download the library and start using it and compare its results to DeepAr and Neural Prophet:

`!pip install neuralforecast` and I got the following error:

ERROR: Could not find a version that satisfies the requirement neuralforecast (from versions: none)
ERROR: No matching distribution found for neuralforecast</div>

**Comment by FedericoGarza** [comment]
Hi @Msaleh87!

Thanks for reporting the issue. I think that maybe it is related to the python version. What version are you using? :)

**Comment by Msaleh87** [comment]
Hi @FedericoGarza, 
I figured, I am using Python 3.6.7, because GluonTs and mxnet work with this version, this is how I was able to run DeepAr. Do I need to use another version or there is a workaround for this?
Thanks

**Comment by FedericoGarza** [comment]
I see. The minimum version supported by neuralforecast is python 3.7. I think gluonts is also compatible with that version.

**Comment by Msaleh87** [comment]
I tried to check the documentation to see the supported version of python, but the documentation didn't mention. I was looking here: https://nixtla.github.io/neuralforecast/

**Comment by FedericoGarza** [comment]
Nice! Thank you for noticing that the python version is missing in the documentation. We will update it.

Let us know if we can help you with anything else. In the next weeks, we'll release a new version of neuralforecast with new and interesting features. :)

**Comment by Msaleh87** [comment]
![image](https://user-images.githubusercontent.com/42920113/190260042-b729be59-d48e-42fd-b1d2-92e41b82329c.png)

I tried version 3.7 and now I am getting this error!

**Comment by Msaleh87** [comment]
Okay, I downloaded Python 3.8 (64-bits, which matches my operating system) and the installation worked. I will leave this comment for others' reference.
