### ISSUE TITLE
neuralforecast 

### ISSUE THREAD

**Issue by alfredaita** [Nixtla/neuralforecast#289]
How would I adjust the epochs in any of the models.
It seems to be set to 1000 by torch.

  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kdgutier** [comment]
Hi @alfredaita,

`models.NeuralForecast` classes allow you to give `**trainer_kwarg` arguments to them, that are later used by a Pytorch Lightning trainer by the `core.Neuralforecast` 's`fit` method.
Here is an example where we set the `max_epochs=100`: 
https://nixtla.github.io/neuralforecast/examples/getting_started_with_nbeats_and_nhits.html

We are still working on the documentation, sorry for the inconvenience

**Comment by alfredaita** [comment]
thank you
