### ISSUE TITLE
Most links missing in README.md

### ISSUE THREAD

**Issue by hertelm** [Nixtla/neuralforecast#290]
Hi, most links in the README.md link to https://github.com/Nixtla/neuralforecast/blob/main/xXmissingXx, for example this one: https://github.com/Nixtla/neuralforecast/blob/main/README.md?plain=1#L56

**Comment by kdgutier** [comment]
Hi @hertelm,

Thanks for pointing that out. Here is the quick start notebook:
https://github.com/Nixtla/neuralforecast/blob/main/nbs/examples/Getting_Started_with_NBEATS_and_NHITS.ipynb

We are working on improving the [documentation](https://nixtla.github.io/neuralforecast/) and tutorials.
