### ISSUE TITLE
Example notebook fails on Colab runtime with GPU "RuntimeError: Expected all tensors to be on the same device"

### ISSUE THREAD

**Issue by jfogelberg** [Nixtla/neuralforecast#307]
**Describe the bug**
Running example notebook nbs/examples/UncertaintyIntervals.ipynb on Google Colab with GPU generates the error below.
The issue seems to be related to the **MQLoss**.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-9-a05534e5c6e2>](https://localhost:8080/#) in <module>
----> 1 fcst.fit(df=Y_train_df)

33 frames
[/usr/local/lib/python3.7/dist-packages/neuralforecast/losses/pytorch.py](https://localhost:8080/#) in __call__(self, y, y_hat, mask)
    418         sq     = torch.maximum(-error, torch.zeros_like(error))
    419         s1_q   = torch.maximum(error, torch.zeros_like(error))
--> 420         mqloss = (self.quantiles * sq + (1 - self.quantiles) * s1_q)
    421 
    422         # Match y/weights dimensions and compute weighted average

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**To Reproduce**
1. Open https://github.com/Nixtla/neuralforecast/tree/main/nbs/examples/UncertaintyIntervals.ipynb
2. Click "Open in Colab"
3. Set Colab runtime to include GPU
4. Run notebook
5. Error occurs when trying to fit the model

**Comment by kdgutier** [comment]
Hi @jfogelberg,

Thanks a lot for reporting this issue we are fixing it in this [PR](https://github.com/Nixtla/neuralforecast/pull/311).

We will update pip/conda with the fix, meanwhile you can run the example installing NeuralForecast with this line:
```
!pip install pip install git+https://github.com/Nixtla/neuralforecast.git@main
```
