### ISSUE TITLE
broken example for `TFT`

### ISSUE THREAD

**Issue by deven-gqc** [Nixtla/neuralforecast#315]
Hello,

I was trying to try the demo code for the `Temporal Fusion Transformer` and the [example given in the docs](https://nixtla.github.io/neuralforecast/models.tft.html#usage-example) is broken. 
1. There is a missing import `from neuralforecast.models import TFT`
2. I'm unable to call the `fit` method as the function does take the `static_df` argument. I checked the source code to see if the argument was renamed, but unfortunately that isn't the case.

![image](https://user-images.githubusercontent.com/86305049/199345395-855bed34-e2d5-42a4-956e-c9c9b230bd32.png)

![image](https://user-images.githubusercontent.com/86305049/199345432-e9a17d01-fe04-4838-89d7-fac907c0a9ef.png)

Thanks!

**Comment by kdgutier** [comment]
Hi @deven-gqc 

Can you try changing the pip install at the top for this line:
```
!pip install git+https://github.com/Nixtla/neuralforecast.git@main
```

The pip/conda version might be outdated.

**Comment by deven-gqc** [comment]
@kdgutier The `fit` method works now, but the plotting after needs a minor fix. 

![image](https://user-images.githubusercontent.com/86305049/199346505-d2876154-47ad-4a48-9e77-18189444a25a.png)

The name of the column is `TFT-hi-90.0`

**Comment by kdgutier** [comment]
Thanks for noticing it, we recently fixed the loss modules to be automatically moving from CPU/GPU devices. 
The conversion back to generate the column names transforms data to float and adds the extra 0.
I will update the example.

**Comment by kdgutier** [comment]
I recommend you to check the `scaler_type='robust'` argument as some of the `TFT` activations benefit from scaling and the default for other window-based models is set to None.
[TFT documentation here](https://nixtla.github.io/neuralforecast/models.tft.html)
