### ISSUE TITLE
About n-hits

### ISSUE THREAD

**Issue by signalworker123** [Nixtla/neuralforecast#321]
I am confuse about this line ：
n_theta = (input_size + max(h//n_freq_downsample[i], 1) )  in n-hits.

I think the n_theta is larger than the input_size , but freq_downsample doesn't mean the output_size should smaller than input_size?
I mean inorder to do Interpolation-----the up-sampling?
Can you help me ? Thank you!!

**Comment by kdgutier** [comment]
Hi @signalworker123,

The number of `NHITS`' backcast+forecast coefficients is determined by:
```
n_theta = (input_size + max(h//n_freq_downsample[i], 1) )
``` 

In the `NBEATS`, the coefficients would be:
```
n_theta = (input_size + h)
```

[Right before interpolation](https://github.com/Nixtla/neuralforecast/blob/main/neuralforecast/models/nhits.py#L29) we parse the backcast and forecast coefficients:
```
backcast = theta[:, :self.backcast_size]
knots = theta[:, self.backcast_size:]
```

That we then interpolate.

**Comment by signalworker123** [comment]
Thank you!!
