### ISSUE TITLE
When I try the RNN demo,this occur:

### ISSUE THREAD

**Issue by signalworker123** [Nixtla/neuralforecast#326]
When I try the RNN demo,this occur:
---------------------------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_36184\146218260.py in <module>
     29     freq='M'
     30 )
---> 31 fcst.fit(df=Y_train_df, static_df=AirPassengersStatic)
     32 forecasts = fcst.predict(futr_df=Y_test_df)

TypeError: fit() got an unexpected keyword argument 'static_df'
-------------------------------------------------------------------------------------------------------
the code is:
https://nixtla.github.io/neuralforecast/models.rnn.html#usage-example
------------------------------------------------------------------------------------------------------
what should I do to solve this problem?
please help me, thank you!!

**Comment by kdgutier** [comment]
Hi @signalworker123 

We are yet to update conda and pip, can you try this line:
```
!pip install git+https://github.com/Nixtla/neuralforecast.git@main
```

**Comment by kdgutier** [comment]
Hi @signalworker123,

We updated the NeuralForecast pip version, all the models now support static, historic and future exogenous variables.
Now installation works with a simple:
```
!pip install neuralforecast
```
