### ISSUE TITLE
default_config does not work for AutoNHITS and AutoNBEATS

### ISSUE THREAD

**Issue by xiao-he** [Nixtla/neuralforecast#337]
While running the colab of AutoNHITS with AutoNHITS.default_config, I have the following error.

  File "autoNbeats.py", line 43, in train
    fcst_df = fcst.cross_validation(df=self.df, val_size=val_size,
  File "/anaconda3/lib/python3.8/site-packages/neuralforecast/core.py", line 158, in cross_validation
    cols += [type(model).__name__ + n for n in model.loss.output_names]
AttributeError: 'Categorical' object has no attribute 'output_names'

**Comment by xiao-he** [comment]
The same error happens for AutoNBEATS, can you also suggest the config contents for AutoNBEATS?

**Comment by vali-hoffi** [comment]
I had the same problem. Got around it by copying the AutoNHITS.default_config and deleting the "normalize" and "loss" and parameter.
But not sure why it works, maybe someone with a better understanding can help...

    default_config = {
       "input_size_multiplier": [1, 2, 3, 4, 5],
       "h": None,
       "n_pool_kernel_size": tune.choice([3*[1], 3*[2], 3*[4], 
                                          [8, 4, 1], [16, 8, 1]]),
       "n_freq_downsample": tune.choice([[168, 24, 1], [24, 12, 1], 
                                         [180, 60, 1], [60, 8, 1], 
                                         [40, 20, 1], [1, 1, 1]]),
       "learning_rate": tune.loguniform(1e-4, 1e-1),
       **#"normalize": tune.choice([True, False]),**
       "max_steps": tune.choice([500, 1000]),
       "batch_size": tune.choice([32, 64, 128, 256]),
       "windows_batch_size": tune.choice([128, 256, 512, 1024]),
       **#"loss": tune.choice([MAE(), MSE()]),**
       "random_seed": tune.randint(1, 20),
    }

**Comment by cchallu** [comment]
Hi @vali-hoffi. We solved the bug in the latest changes. Now, the Auto classes only allow one loss and need to be specified in the initialization of the model.
