### ISSUE TITLE
NBEATSx exogenous stack question

### ISSUE THREAD

**Issue by shpp9212** [Nixtla/neuralforecast#338]
Hi, I have a question about using NBEATSx.
I am confused from different terminologies between the codes and the paper.
Is the 'identity' stack the 'exogenous' stack in the paper?
Thanks in advance.

**Comment by shpp9212** [comment]
Hi, I believe I missed the generic configuration part from the paper.
I now guess that the exogenous stack is not implemented in neuralforecast yet. Is this correct?
If yes, could you recommend a package which fully implement the NBEATSx?
Thanks.

**Comment by kdgutier** [comment]
Hi @shpp9212,

Thanks for opening this issue. For the moment we don't have the `NBEATSx` class with the interpretable configuration.
Meanwhile, this repository has the complete model configurations and the replication of its paper experiments:

-[NBEATSx paper repository](https://github.com/cchallu/nbeatsx/tree/main/src/utils)
-[Kin G. Oivares, Cristian Challu, Grzegorz Marcjasz, Rafał Weron, Artur Dubrawski (2022). "Neural basis expansion analysis with exogenous variables: Forecasting electricity prices with NBEATSx". International Journal of Forecasting.](https://www.sciencedirect.com/science/article/pii/S0169207022000413)
