### ISSUE TITLE
Failing studentt_domain_map

### ISSUE THREAD

**Issue by dluuo** [Nixtla/neuralforecast#346]
When I try to use the DistributionLoss with 'StudentT' parameter with NHITS, I get the following error:

![image](https://user-images.githubusercontent.com/60141418/205159513-4b8e461d-0778-4c6d-9691-70e699b31385.png)

**Comment by kdgutier** [comment]
The `loss.scale_decouple` method now incorporates the StudentT's parameter domain protection.
