### ISSUE TITLE
'LongHorizon_Probabilistic.ipynb' - Example Notebook Update

### ISSUE THREAD

**Issue by PotosnakW** [Nixtla/neuralforecast#371]
**Describe the bug**
Loss parameter should be moved from the config variable to the 'AutoNHITS initialization in the 'NeuralForecast' object.

**To Reproduce**
1. Run 'LongHorizon_Probabilistic.ipynb' 
2. Perform cross validation 
3. See error: 'Please use `loss` argument instead of `config['loss']`

**Expected behavior**
Model(s) are trained via cross validation without a raised issue.

**Screenshots**
Current notebook issue location:
<img width="1081" alt="Screen Shot 2022-12-15 at 11 05 55 AM" src="https://user-images.githubusercontent.com/71658863/207910154-264e51ba-7358-465d-8b46-7f5cced68b1c.png">

Recommend update:
<img width="1065" alt="Screen Shot 2022-12-15 at 11 06 35 AM" src="https://user-images.githubusercontent.com/71658863/207910127-4d3e7352-a4e3-4f29-a0c6-8780e868f86f.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: safari
 - Version: 12.3

**Comment by vali-hoffi** [comment]
Should be implemented with version 1.3. #372
