### ISSUE TITLE
Multivariate Time Series

### ISSUE THREAD

**Issue by asifmustafa87** [Nixtla/neuralforecast#384]
Hi,

I want to know like if Nixtla supports Multivariate Time Series Forecasting. If so, where can I find the workout examples?

**Comment by kdgutier** [comment]
Hi @asifmustafa87,

1. All NeuralForecast's models use [cross-learning optimization](https://www.sciencedirect.com/science/article/pii/S0169207020301850), you can think of them as multivariate/global models.

2. Additionally you can use the exogenous variables inputs to leverage predictive correlations across series, here is an [exogenous variables example notebook](https://github.com/Nixtla/neuralforecast/blob/main/nbs/examples/Exogenous_Variables.ipynb).

3. We are still working to allow the network's outputs to accept multivariate distributions, or multivariate losses.

Let me know if this helps.

**Comment by candalfigomoro** [comment]
Hi @kdgutier ,

in [Darts](https://unit8co.github.io/darts/) you can use multivariate timeseries so that "_each dimension consumes the (lagged) values of all other dimensions_".

Is there an easy way to do this in neuralforecast (as in Darts), or do we have to do it manually by adding the other time series as exogenous variables to each time series?

Thanks

**Comment by kdgutier** [comment]
Hi @candalfigomoro,

Thanks for using `NeuralForecast`.
We are currently working towards a full-multivariate model if you want to try it check this notebook:
- https://github.com/Nixtla/neuralforecast/blob/main/nbs/models.stemgnn.ipynb

In my experience unless the dataset has plenty of Granger-causal relationships a Vector Autoregressive approach tends to make the models unnecessary complicated, as the models tries to learn noisy cross-series relationships. I would definitely compare the predictions of the full-multivariate model to one where you manually feed the model the exogenous variables through the `stat_exog_list, hist_exog_list, futr_exog_list` parameters.
