### ISSUE TITLE
Add get_params to Distribution loss

### ISSUE THREAD

**Issue by cchallu** [Nixtla/neuralforecast#398]
Complete `get_params` method placeholder with scaled parameters.

**Comment by kdgutier** [comment]
The `loss.scale_decouple` method is now implicitly acting as the `get_params` method:
```
distr_args = self.loss.scale_decouple(output=output, loc=y_loc, scale=y_scale)
```

See:
- [BaseWindow's train/validation/predict steps](https://github.com/Nixtla/neuralforecast/blob/main/nbs/common.base_windows.ipynb)
- [BaseRecurrent's train/validation/predict steps](https://github.com/Nixtla/neuralforecast/blob/main/nbs/common.base_recurrent.ipynb)
