### ISSUE TITLE
AutoNHITS Failing, Tune Failed

### ISSUE THREAD

**Issue by dluuo** [Nixtla/neuralforecast#403]
I tried to run AutoNHITS with this following configuration:
![image](https://user-images.githubusercontent.com/60141418/212229096-babf62ea-1cbc-4368-bc08-ab4ea772006c.png)
But i get the following error:
![image](https://user-images.githubusercontent.com/60141418/212229154-b4d849e6-7d64-4de8-8db8-fad6f1b2b100.png)

I am not sure why this is happening

**Comment by grahamsparrow-8451** [comment]
I also see this problem intermittently. I have seen it with AutoTFT as well as AutoNHITS. Sometimes it successfully runs many tuning iterations, other times it fails.

**Comment by grahamsparrow-8451** [comment]
I can't be sure that the problem has gone away as, at least for me, it was intermittent. However, I just installed the latest from github main (`pip install git+https://github.com/Nixtla/neuralforecast`) and ran 100 iterations of hyperparameter tuning (`num_samples=100`) without any failures. @dluuo, worth trying this.
