### ISSUE TITLE
out of sample and autoregressive block

### ISSUE THREAD

**Issue by waudinio27** [Nixtla/neuralforecast#411]
DEAR team, 
this is a great collection. Could you add to the easy start an out of sample prediction as well after the test part?
Has the team thought of adding an autoregressive block/stack to the N-HiTS model to imporve the forecasts? I think this would be a great feature. Like in the sturctural time series of tensorflow probability :-D

**Comment by kdgutier** [comment]
Hi @waudinio27,

We are glad to hear that the NeuralForecast library is of service.
Thanks for the suggestion, we will work on a notebook example for out of sample predictions.

In the meantime you can take a look to the `core.prediction` method that provides the functionality. Here is the documentation:
https://nixtla.github.io/statsforecast/core.html

**Comment by waudinio27** [comment]
Wau thank you so much for your fast reply! I will try my best. Keep up the good work.
