### ISSUE TITLE
data stored in numpy arrays x and y (and not a table)

### ISSUE THREAD

**Issue by max6457** [Nixtla/neuralforecast#433]
Hello,
I have the problem that my data is stored in two numpy arrays: x and y. 
The data cannot be stored in a table, it has to be two different arrays, one for the input(x) and one for the output(y). 
I wanted to ask how I can fit such a data in your models, in tensorflow it would be like "model.fit(x,y)"...

**Comment by cchallu** [comment]
Hello,

We have the following tutorials on data inputs: https://nixtla.github.io/neuralforecast/examples/data_format.html and https://nixtla.github.io/neuralforecast/examples/exogenous_variables.html.

All our models need a Pandas dataframe with at least the following three columns: `unique_id`, `ds`, and `y`. You can specify other covariates as additional columns.

**Comment by cchallu** [comment]
The datestamp column `ds` doesn't need to be actual real dates, it is only used for sorting the observations. You can set `ds` as 1, 2, 3, ...

For the `unique_id` the actual values doesn't matter, it is only used to identify different time-series.
