### ISSUE TITLE
Add normalized metrics

### ISSUE THREAD

**Issue by leejoonhun** [Nixtla/neuralforecast#474]
It would be nice if there are normalized metrics such as normalized deviation and normalized rmse.
I implemented it, but I don't know where to assign these the type of error, so I won't PR.
If you tell me the category of ND or NRMSE, I will promote the implemented code :)

**Comment by kdgutier** [comment]
Hi @leejoonhun ,

We recently included two normalized metrics the scaled Continuous Ranked Probability Score (sCRPS)
and the mean Squared Scaled Error (MSSE). There are other relative metrics available too like 

Here is the documentation of the relative error metrics: 
- https://nixtla.github.io/neuralforecast/losses.pytorch.html#scale-independent-errors
- https://nixtla.github.io/neuralforecast/losses.pytorch.html#scrps.__init__

**Comment by leejoonhun** [comment]
Oh, sorry for the stupid question..
ND and NRMSE appear in [this paper](https://papers.nips.cc/paper/2016/hash/85422afb467e9456013a2a51d4dff702-Abstract.html).

**Comment by kdgutier** [comment]
I think the paper does not write the NRMSE equation, from what I see there are several versions:
https://stats.stackexchange.com/questions/116238/normalized-rmse

**Comment by leejoonhun** [comment]
I implemented first version of the link, but I didn't know there were many versions..
It may be misunderstood, so I don't think they need to be added :)

**Comment by kdgutier** [comment]
Would you be able to share your first version implementation?
We could make it available in the next PR, it does not matter if it is in numpy we have pytorch and numpy mirror.
