### ISSUE TITLE
fitted values for ESRNN

### ISSUE THREAD

**Issue by Yasslight90** [Nixtla/neuralforecast#475]
Hi,

I would like to know if it is possible to obtain the fitted_values from ESRNN ?

Thanks

**Comment by kdgutier** [comment]
Hi @Yasslight90,

We are still yet to add the ESRNN into NeuralForecast library.
If you are interested in the model here is our legacy implementation: https://github.com/kdgutier/esrnn_torch

Regarding fitted values we have the `NeuralForecast.predict_rolled` method, that you can use to retrieve fitted values:
https://nixtla.github.io/neuralforecast/core.html#neuralforecast.predict_rolled

**Comment by Yasslight90** [comment]
Thank you. I will check NeuralForecast.predict_rolled. However, NeuralForecast does have ESRNN on its 0.1.0 version; that's what I am using.
