### ISSUE TITLE
TypeError: can only concatenate str (not "pandas._libs.tslibs.offsets.MonthEnd") to str

### ISSUE THREAD

**Issue by beergil** [Nixtla/neuralforecast#484]
Hello,
I am trying to replicate the Automatic Hyperparameter Tuning using my dataset but encountered this error when using the predict method to forecast the next 12 months......

![Screenshot 2023-03-25 001818](https://user-images.githubusercontent.com/57521388/227582671-9c668d26-9b20-4080-b225-62ff785a76dd.png)
![Screenshot 2023-03-25 001741](https://user-images.githubusercontent.com/57521388/227582682-d9a35c3e-8ada-48f3-8f4d-0a5340dfc95f.png)

**Comment by FedericoGarza** [comment]
hey @beergil! The issue probably arises due to your `ds` column type. You could try `Y_df['ds'] = pd.to_datetime(Y_df['ds'])` to convert it to `datetime` type.

**Comment by rnjv** [comment]
I have the same issue:

![image](https://user-images.githubusercontent.com/3862237/236634552-3b4a11e2-594d-442b-89d6-8af270b15710.png)

![image](https://user-images.githubusercontent.com/3862237/236634636-5ca6e5eb-e60a-4a3e-90f3-d2f328826d39.png)

**Comment by legel** [comment]
The solution from @FedericoGarza above worked.

**Comment by jmoralez** [comment]
Closing since casting to datetime seems to solve the issue. Feel free to reopen if you run into this issue again.
