### ISSUE TITLE
Hierarchical reconciliation and nhits tutorials don't run in colab from the links provided

### ISSUE THREAD

**Issue by jzicker** [Nixtla/neuralforecast#514]
I was attempting to run some of the tutorial examples.  The first two that I tried were for n-hits and hierarchicaI and both produced errors.   All I was going was stepping through the cells.   For example augment_calendar_df was listed as not found.

Guessing someone hasn't looked at the current updates and installations.

I was really excited about this effort and totally stalled out!

**Comment by kdgutier** [comment]
Hi @jzicker,

Sorry for the inconvenience with the missing `augment_calendar_df` method.
The method is available in the main branch and you can install it with this line:
``` !pip install git+https://github.com/Nixtla/neuralforecast.git ```

**Comment by jzicker** [comment]
That fixed the problem.   Posted another one for the long horizon tutorial

**Comment by kdgutier** [comment]
Thanks for reporting the issue @jzicker, I will update the tutorial with the correct installation.
