### ISSUE TITLE
NHits Bug: only possible stack_type is `identity` 

### ISSUE THREAD

**Issue by mr-1993** [Nixtla/neuralforecast#518]
Hi, 

concerning the NHits-Model, `stack_types` is a parameter, but only the identity stack type is available. Is this intended? 

Thanks a lot in advance!

**Comment by kdgutier** [comment]
Hi @mr-1993,

In contrast to an NBEATS-i model that performs projections into the polynomial and harmonic basis to recover a trend and a seasonality component, the NHITS model performs projections into frequency-specialized stacks controlled by the interpolation (closely related to the Wavelet transform).

We explain the principle in the description of the Hierarchical Interpolation technique in Section 3 of the NHITS paper.
https://arxiv.org/pdf/2201.12886.pdf

If you are interested in recovering decomposition plots, here is a Jupyter notebook with an example:
https://github.com/Nixtla/neuralforecast/blob/main/nbs/models.nhits.ipynb
