### ISSUE TITLE
Autoformer bug, Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by max6457** [Nixtla/neuralforecast#522]
Hello,
when I try to train with the Autoformer model, as always with the other models, I get the following RunetimeError:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)

![image](https://user-images.githubusercontent.com/122063689/232169548-c1e2814f-2b47-4302-a373-e1b106de03fe.png)

**Comment by kdgutier** [comment]
Hey @max6457,

I fixed the Autoformer memory bug. 

To import the code changes install neuralforecast with this instruction:
```!pip install git+https://github.com/Nixtla/neuralforecast.git@fix/autoformer```

**Comment by max6457** [comment]
Thank you very much! This is a truly amazing package :)

**Comment by max6457** [comment]
Informer has the same problem :)

**Comment by kdgutier** [comment]
Hey @max6457,

Thanks for reporting the bug, the fix is now availalble in this branch:
```!pip install git+https://github.com/Nixtla/neuralforecast.git@fix/autoformer```

**Comment by DKorman** [comment]
Hi! I have the same issue using NHITS with DistributionLoss(Poisson) and DistributionLoss(Tweedie)

**Comment by kdgutier** [comment]
Hey @DKorman 

Thanks for using the library. I believe I fixed the issue on the latest main update.
- What version of NeuralForecast are you using?
- Can you try install from main `!pip install git+https://github.com/Nixtla/neuralforecast.git`

If the problem persists can you provide more information on the bug?

**Comment by james-l-wei** [comment]
Hi, I have updated to the latest version of the neuralforecast package but I am receiving the same error message for VanillaTransformer using default settings.

![image](https://user-images.githubusercontent.com/66972060/236679514-88f94fa4-f2cf-4bac-90df-273b60d586cd.png)

**Comment by kdgutier** [comment]
Hey @james-l-wei,

Thanks for reporting the bug, I am attending it.
