### ISSUE TITLE
How predict_rolled works

### ISSUE THREAD

**Issue by tinased95** [Nixtla/neuralforecast#537]
Could you please explain how predict_rolled would work if I pass n_windows and step_size to predict multiple steps ahead? Lets say my data is hourly and the model predicts for the next day. If I want to get predictions for the next 30 days I could use predict_rolled(df, window_size=30*24, step_size=24) to get the predictions. My question is will the model use measured data of the previous window to predict the next samples or use its predictions to predict the next window? I know that for the first sequence it will definitely use measured data but for predicting next sequences does it use its previous predictions or measured data as input?
Thanks.

**Comment by kdgutier** [comment]
Hi @tinased95,

We are working on an updated version of the `predict_rolled` method.
We will deprecate it soon in favor of a `predict_insample` method that generates the rolling predictions of dimensions 
[n_series, n_time, horizon] or when you send step_size [n_series, n_time//step_size, horizon] in flattened format.

This is the PR https://github.com/Nixtla/neuralforecast/pull/528.

**Comment by tinased95** [comment]
Thanks for your response. My question is regarding rolling predictions; Does the model use measured data each time moving forward in time or use its previous predictions as the input to predict the next sequence?

**Comment by kdgutier** [comment]
Currently, all our models employ a multi-step forecast strategy, which involves generating a forecast in multiple steps or stages. This approach allows us to create a forecast in a single forward pass, resulting in faster predictions, compared to the recurrent version.

The strategy is depicted here:
https://nixtla.github.io/neuralforecast/models.dilated_rnn.html

**Comment by tinased95** [comment]
Thanks. Based on the paper you shared, which strategy are you using for multi-step forecasting in predict_rolled method?

**Comment by kdgutier** [comment]
Most networks use an MLP decoder that creates the whole forecast horizon in a single pass.

**Comment by tinased95** [comment]
I apologize for any confusion, but I'm still unclear on the name of the strategy being used in predict_rolled. Would it be possible for you to kindly share that information with me? Thank you.

**Comment by cchallu** [comment]
Hi @tinased95! If you want to make several historical predictions, you can use the `cross_validation` function. To make daily forecasts for one month, you can set the following hyperparameters of the function: `n_windows=30` and `step_size=24`.

Here is an explanation: the first prediction will be made at the timestamp T-30*24 hours (where T is the length of your data), and it will use all the information before that point to forecast. It will then "move" to T-29*24 and produce the forecast again with the latest available data. Note that this function only works for historical data. We do not yet have a function to iteratively forecast longer horizons (than h) and concatenate the forecast. I hope this helps.

**Comment by tinased95** [comment]
Thank you so much for your response.
