### ISSUE TITLE
Why does the documentation say that the static_df should contain `ds` column?

### ISSUE THREAD

**Issue by ntubiolin** [Nixtla/neuralforecast#538]
Hi! I really like this open source repo because it contains many tutorials. 
However, when I am reading the docstring of the [core.py](https://github.com/Nixtla/neuralforecast/blob/main/neuralforecast/core.py#L187), I come up with a question: 
Why does the documentation say that the static_df should contain `ds` column?

I don't know the answer yet, but I find the frequently-used `static_df`, `neuralforecast.utils.AirPassengersStatic`, contains no `ds` information. 
Should the documentation be updated? Or can someone elaborate the docstring of `static_df` for me? Thanks.

**Comment by kdgutier** [comment]
Thank you for bringing the error in the documentation to our attention. We apologize for any confusion it may have caused. 

To clarify, the `static_df` is intended to hold static information that is associated with the `unique_id` series. As such, it is not dependent on the date stamps `ds`. We appreciate your feedback and will update the documentation.

**Comment by ntubiolin** [comment]
Thanks!
