### ISSUE TITLE
No multivariate version on ETTh datasets

### ISSUE THREAD

**Issue by wtestererer** [Nixtla/neuralforecast#547]
Hi there is no multivariate version on ETTh datasets but only univariate datasets

**Comment by kdgutier** [comment]
Hi @wtestererer,

Thanks for the inquiry. As we mention on the discussion Section of the [NHITS paper](https://arxiv.org/abs/2201.12886), NHITS is a purely univariate method.

The baselines use the same panel data on which we train and evaluate the NHITS and train the methods as multivariate.

**Comment by kdgutier** [comment]
Here are the experiments of NHITS on the multivariate datasets.
https://github.com/cchallu/n-hits/blob/main/nhits_multivariate.py

You can also replicate similar results in Google Colab, with the NHITS tutorial:
https://nixtla.github.io/neuralforecast/examples/longhorizon_with_nhits.html
