### ISSUE TITLE
Duplicate median in HINT example

### ISSUE THREAD

**Issue by candalfigomoro** [Nixtla/neuralforecast#548]
In this example: https://nixtla.github.io/neuralforecast/examples/hierarchicalnetworks.html

We have
```
level = np.arange(0, 100, 2)
qs = [[50-lv/2, 50+lv/2] for lv in level]
quantiles = np.sort(np.concatenate(qs)/100)
```

This code creates two "0.5" values in the quantiles array.

So, after calling `predict()`, we get two "median" columns with the same name (and having a pandas DataFrame with 2 columns with the same name is not a very good practice).

Is this expected?

**Comment by kdgutier** [comment]
Thanks for reporting the bug @candalfigomoro. I will correct it.
