### ISSUE TITLE
Bugs in robust_scaler and invariant_scaler

### ISSUE THREAD

**Issue by yoheyokubo** [Nixtla/neuralforecast#550]
Each of the following lines seems to calculate the _median absolute deviation_ (mad) when the mad is equal to zero (that is, when more than half of the data have an equal value). However, according to [the relationship between the std and the mad in the case of normal distribution](https://en.wikipedia.org/wiki/Median_absolute_deviation), this should be multiplication, not division, isn't it?
https://github.com/Nixtla/neuralforecast/blob/7233b6cdff6954baa3c2f02d169bc580763fa961/neuralforecast/common/_scalers.py#L206
https://github.com/Nixtla/neuralforecast/blob/7233b6cdff6954baa3c2f02d169bc580763fa961/neuralforecast/common/_scalers.py#L251

In addition, the documentation corresponding to each says that the mad stands for the _mean absolute deviation_. Isn't _mean_ mistake of _median_?
Regards

**Comment by kdgutier** [comment]
Hey @yoheyokubo,

Thanks for catching the bug 🐛.
