### ISSUE TITLE
Issues with N-BEATSx and N-HITSx component analysis

### ISSUE THREAD

**Issue by sdmishra123** [Nixtla/neuralforecast#566]
Hello,

I was able to get the Level/Trend/Seasonal components for my model (NBEATS without exogs) using the link you shared, but I need help to get the components for my model (NBEATSx with exogs).
I keep getting the error - "RuntimeError: maximum size for tensor at dimension 2 is 280, but the size is 336",
when I run this line of code y_hat = nbeatsx.decompose(dataset=dataset). 

I used the below links to generate the components.

https://github.com/Nixtla/neuralforecast/blob/main/nbs/models.nhits.ipynb
https://github.com/Nixtla/neuralforecast/blob/main/nbs/models.nbeats.ipynb

In the below image, what does identity represent in N-BEATS? 
Why do I see seasonality in the trend component?

![N-BEATS component Analysis](https://github.com/Nixtla/neuralforecast/assets/61155429/304a1bc7-7200-4180-8798-74ec169cdaa1)

I have one more question, is there a way to get the feature importance for the exogenous variables used in the N-BEATSx and N-HITS model?

**Comment by kdgutier** [comment]
Hey @sdmishra123,

Thanks for using for trying out the NBEATS decomposition.

**Regarding the `RuntimeError: maximum size for tensor at dimension 2 is 280, but the size is 336`**
- For the moment we are yet to include the exogenous partial predictions, as the current version of NBEATSx is not performing the projections on the exogenous basis, rather its taking the exogenous data as inputs of the MLPs.
- We will get to work on this feature soon.

**What does identity represent in NBEATS?**
- As you may know the interpretable NBEATS model is performing a decomposition, learning projection coefficients into polynomial and harmonic functions. $y_{[t+1:t+h]} = \alpha Poly +  \beta Sin/Cos$. In the case of and identity basis all the decoder is allowed to be freely determined that is $y_{[t+1:t+h]} = [\theta_{1},\theta_{2},...,\theta_{h}]$


**Why do I see seasonality in the trend component?**
- Your NBEATS model might not have been properly trained, you may want to look to the `AutoNBEATS` model, to automatically explored learning rate and training steps. Here is the [AutoNBEATS documentation](https://nixtla.github.io/neuralforecast/models.html#autonbeats), and here is an [AutoNBEATS usage example](https://nixtla.github.io/neuralforecast/examples/longhorizon_with_nhits.html).

**Is there a way to get the feature importance for the exogenous variables used in the N-BEATSx and N-HITS model?**
- Regarding the feature importance capabilities, one could obtain a relative importance by taking partial predictions and dividing them by the total predictions. We have not done such an analysis yet.

**Comment by sdmishra123** [comment]
Thanks a lot for your prompt reply! This was very helpful. I re-ran my model and generated the decomposition plot. It looks fine now.

**Comment by kdgutier** [comment]
Glad to help.

**Comment by aliozanmemeto** [comment]
This still does not work with stat_exog_list
