### ISSUE TITLE
NHITS giving different results each time I train and predict

### ISSUE THREAD

**Issue by ShreyaMathur-code** [Nixtla/neuralforecast#570]
I'm training the following NHITS Model for my daily dataset (input_y):

nhits = NHITS(h=56, input_size=392, random_seed=42) #using default values for other hyperparameters
fcst = NeuralForecast(models=[nhits],freq='D')
fcst.fit(df=input_y) 
pred_nhits = fcst.predict(random_seed=42)

I ran this multiple times and am getting different predicted values each time. Is it possible to get the same stable results every time I run it. How can I achieve that?

Thanks in advance. Appreciate your help!

**Comment by kdgutier** [comment]
Hey @ShreyaMathur-code,

Thanks for using NeuralForecast, in principle the execution of your code should be replicable.
- It is using MAE, and the output is deterministic.
- You are using NF without tune.

Can you provide more details?

**Comment by ShreyaMathur-code** [comment]
Sure, I ran a very simple NHITS model as stated above and was unable to replicate my results. 

- It is using MAE, and the output is deterministic - that's my understanding, the model should take loss=MAE() by default as stated in the documentation - https://nixtla.github.io/neuralforecast/models.nhits.html
- You are using NF without tune - that's right I'm only specifying a single value for input size and random seed.

Could you please specify what more information you would need, I'll try to provide it quickly. 

Thankyou for your prompt response.

**Comment by ShreyaMathur-code** [comment]
I tested for NBEATS as well. NBEATS produces the same exact result for the same set of input, however NHITS does not. Is there a particular hyperparamater in NHITS that introduces some randomness to the model?

**Comment by rnjv** [comment]
Faced the same issue, I "fixed" it by using a MQLoss().

**Comment by cchallu** [comment]
HI @ShreyaMathur-code. I was not able to replicate your problem. Every time I ran `NHITS` (or other models, on both CPU and GPU), it produced the same results, even with the MQLoss. You can check this using our Getting Started example on Colab, by clicking the "Open in Colab" button: https://nixtla.github.io/neuralforecast/examples/getting_started.html. 

I believe there must be another source of variation in your pipeline, maybe the data you are reading is changing.

**Comment by ShreyaMathur-code** [comment]
Thankyou so much Cristian, like you had mentioned it is due to GPU cluster instability. Somehow NBEATS is working fine on GPU cluster for us, however, NHITS is not. I know I've already taken quite a bit of your time, but if you have any other recommendation do let me know. 

Appreciate your help. Thanks!
