### ISSUE TITLE
[Bug] NeuralForecast uses an fairly out of date version of `protobuf` causing confilicts with other packages. 

### ISSUE THREAD

**Issue by harrymyburgh** [Nixtla/neuralforecast#585]
**Describe the bug**
NeuralForecast uses an fairly out of date version of `protobuf` causing confilicts with other packages. This means that one must resort to a dirty fix that decrease the performance of a program. 

**To Reproduce**
1. Use a package that requires a later version of `protobuf`, such as Google ORTools, with NeuralForecast. 
2. Run a program with the aforementioned environment setup (or similar).
**Expected behavior**
An error message with a temporary slow fix will be returned by `protobuf`:
```
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1
 - NeuralForecast Version: 1.5.0

**Comment by kdgutier** [comment]
Hey @harrymyburgh,

Is your bug related to this bug in the ray package?
- https://github.com/ray-project/ray/issues/25282
- https://github.com/ray-project/ray/issues/25638
