### ISSUE TITLE
Mismatching NBEATSx parameters: harmonics/seasonality and polynomials/trend

### ISSUE THREAD

**Issue by rcslight** [Nixtla/neuralforecast#605]
In the [NBEATSx implementation](https://github.com/Nixtla/neuralforecast/blob/main/nbs/models.nbeatsx.ipynb), it reads on the docstrings of the model that:

```python
"""
**Parameters:**
(...)
`n_harmonics`: int, Number of harmonic terms for trend stack type. Note that len(n_harmonics) = len(stack_types). Note that it will only be used if a trend stack is used.
`n_polynomials`: int, Number of polynomial terms for seasonality stack type. Note that len(n_polynomials) = len(stack_types). Note that it will only be used if a seasonality stack is used.
"""
```

When in fact, harmonics are given to `SeasonalityBasis()` and polynomials to `TrendBasis()`.

**Comment by kdgutier** [comment]
Hey @rcslight, 

Thanks for bringing this to our attention. The documentation is now improved.
