### ISSUE TITLE
Predict_insample examples in documentation

### ISSUE THREAD

**Issue by Ftrejo23** [Nixtla/neuralforecast#608]
Hello I know that predict_rolled will soon be depracated and was hoping we can get some examples in the documentation on how to use the predict_insample method. Hopefully there can also be further mention of any limitations when using the method (I have had some issues using it in the past but have since resolved). Thank you for all the hard work!

**Comment by cchallu** [comment]
Hi @Ftrejo23 ! Yes, we are working on new tutorials, including how to use the `predict_insample`. We expect to have this tutorial next week.
