### ISSUE TITLE
Is there any plan to put TiDE algorithm into neuralforecast

### ISSUE THREAD

**Issue by LeonTing1010** [Nixtla/neuralforecast#610]
[TiDE](https://arxiv.org/abs/2304.08424) can provide multiple choices for Neuralforecast. TiDE is a deep learning-based framework for long-term time series forecasting, which uses several powerful deep learning models for prediction. These models include LSTM, GRU, CNN, TCN, Transformer, and more, which have been validated in practice and demonstrated good performance in multiple time series forecasting tasks. Therefore, integrating these models into Neuralforecast can provide more model choices, and the performance of these models can be verified and compared through TiDE's experimental results. At the same time, multiple models from Neuralforecast can also be integrated into TiDE for comparison and analysis, providing more choices and flexibility for time series forecasting tasks. Therefore, TiDE can provide multiple choices for Neuralforecast, further improving the performance and application scope of the predictive models.

**Comment by kdgutier** [comment]
Hey @LeonTing1010, would you be able to provide a pointer to the TiDE model implementation?

**Comment by LeonTing1010** [comment]
I see that google has already implemented. https://github.com/google-research/google-research/tree/master/tide

**Comment by joshua-xia** [comment]
TiDE maybe the most advanced algorithm of time series forecasting, Darts also implementing this model.
https://github.com/unit8co/darts
