### ISSUE TITLE
There is no patchtst in the dictionary

### ISSUE THREAD

**Issue by LeonTing1010** [Nixtla/neuralforecast#612]
File "Test.py", line 9, in long
    nf = NeuralForecast.load(path=f'./checkpoints/test_run/{CODE}/')
  File "/node/SMGPT/.venv/lib/python3.8/site-packages/neuralforecast/core.py", line 723, in load
    MODEL_FILENAME_DICT[model_name].load_from_checkpoint(f"{path}/{model}")
KeyError: 'patchtst'
<img width="719" alt="Screen Shot 2023-06-03 at 13 54 12" src="https://github.com/Nixtla/neuralforecast/assets/1998680/437c5eda-1c75-4338-8f7a-b843582b2e6f">
There is no patchtst in the dictionary

**Comment by kdgutier** [comment]
Hey @LeonTing1010,

Thanks for using the library. The error is fixed in the main branch you can install it using this line:
```
!pip install git+https://github.com/Nixtla/neuralforecast.git
```
