### ISSUE TITLE
AutoNBEATSx not in model dictionary

### ISSUE THREAD

**Issue by upadhyan** [Nixtla/neuralforecast#622]
### What happened + What you expected to happen

When saving an AutoNBEATSx model, it is impossible to read it back in currently as is since you end up getting a `KeyError` since `MODEL_FILENAME_DICT` in `core.py` does not have `autonbeatsx` as a key. 

The current workaround for this is to rename the saved `.ckpt` file from `autonbeatsx_0.ckpt` to `nbeatsx_0.ckpt`, which is mildly annoying. 

### Versions / Dependencies

NeuralForecast 1.5.0

### Reproduction script

```
models = [AutoNBEATSx(h = HORIZON, 
                          loss = MAE(),
                          config = nbeatsx_config_space,
                          num_samples=10)] 
nf = NeuralForecast(models=models, freq='B')
nf.fit(df=train_dataset)

nf.save(path='./nf_models/',
        model_index=None, 
        overwrite=True,
        save_dataset=True)
nf2 = NeuralForecast.load(path='./nf_models/')
```

results in `KeyError: 'autonbeatsx'`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by kdgutier** [comment]
Hey @upadhyan,

Sorry for the inconvenience, I will take a look to add the AutoNBEATSx method.

For the moment you can get the generic version of `NBEATSx-g` to work using an`NHITS` with `n_freq_downsample=1` like this:
```
models = [NHITS(h=horizon,                           # Forecast horizon
                input_size=2 * horizon,              # Length of input sequence
                loss=HuberLoss(),                    # Robust Huber Loss
                max_steps=1000,                      # Number of steps to train
                dropout_prob_theta=0.5,
                interpolation_mode='linear',
                stack_types=['identity']*2,
                n_blocks=[1, 1],
                mlp_units=[[64, 64],[64, 64]],
                n_freq_downsample=[1, 1],           # Inverse expressivity ratios, set to 1 for NBEATSx-g
                val_check_steps=10,                  # Frequency of validation signal (affects early stopping)
              )
          ]
nf = NeuralForecast(models=models, freq='M')
nf.fit(df=Y_train_df)
```
