### ISSUE TITLE
Broken link the README

### ISSUE THREAD

**Issue by axeltorbenson** [Nixtla/neuralforecast#647]
### Description

Broken link in the highlights section of the README file. Says it links to experiments but doesn't.

![image](https://github.com/Nixtla/neuralforecast/assets/72292627/b6fafa57-daed-4bac-ac65-8c02ea91db52)

**Comment by MMenchero** [comment]
This issue has been fixed since the line that had the broken link has been removed. Issue #803 is a duplicate.
