### ISSUE TITLE
Core: NeuralForecast - UncertaintyIntervals

### ISSUE THREAD

**Issue by nsankar** [Nixtla/neuralforecast#648]
### Tutorial documentation error
The example notebook [accessible here](https://colab.research.google.com/github/Nixtla/neuralforecast/blob/main/nbs/examples/UncertaintyIntervals.ipynb#scrollTo=2bd26217-cac6-4460-a1c6-43da680ce25f) mentions the following under Section #4 - Plotting Predictions.
_Consider the output [NHITS-lo-90.0, NHITS-hi-90.0], that represents the 80% prediction interval of the NHITS network; its lower limit gives the 5th percentile (or 0.05 quantile) while its upper limit gives the 95th percentile (or 0.95 quantile). For well-trained models we expect that the target values lie within the interval 90% of the time._

The above interpretation seems to be incorrect. for [NHITS-lo-90.0, NHITS-hi-90.0], the lower limit should be 10th percentile (i.e. lo-90.0) and the upper limit shoud be the 90th percentile (i.e. hi-90.0) instead of 5th and 95th percentiles stated in the notebook. This needs to be corrected.

### Versions / Dependencies

Colab

### Reproduction script

NA

### Issue Severity

Low: It annoys or frustrates me.

**Comment by kdgutier** [comment]
Hey @nsankar,

Our model's follow the forecasting community notation of prediction intervals, still we appreciate the comment.

The prediction intervals accumulate the percentage that defines their name. For example, prediction interval ['-lo-90.0', '-hi-90.0'] accumulate 90 percent of the probability, corresponding to the quantiles q5 and q95, respectively.

An in-detailed explanation of prediction intervals is available here: https://otexts.com/fpp3/prediction-intervals.html

**Comment by nsankar** [comment]
@kdgutier Thanks for the info. and details.
