### ISSUE TITLE
[TimesNet] 

### ISSUE THREAD

**Issue by NQevxvEtg** [Nixtla/neuralforecast#662]
### Description

https://github.com/thuml/TimesNet

### Use case

The model of all models as of now.

**Comment by cchallu** [comment]
Hi @NQevxvEtg, thanks for the suggestion!

We actually talked with the authors of the model at ICLR.

We will add it to the library soon and are very excited about comparing it with other models.

**Comment by NQevxvEtg** [comment]
👀 ok, thanks!
