### ISSUE TITLE
[BUG] Distribution loss seems to spawn tensors on cpu and gpu device

### ISSUE THREAD

**Issue by RobertHaase** [Nixtla/neuralforecast#675]
### What happened + What you expected to happen

i tried to run (with cuda enabled) the tutorial for intermittent timeseries  https://nixtla.github.io/neuralforecast/examples/intermittentdata.html and couldnt execute the tutorial completely. When i try to execute the fit method, an error gets thrown:

> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Re-running the tutorial with another loss defined e.g. with the neuralforecast.losses.pytorch.MQLoss, the model trainings runs just fine! So i suppose there is a bug with the DistributionLoss which is used in this tutorial.

The logs are the following:

> File ~/Pycharm_projects/paretos-demand/.venv_test/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py:287, in _call_strategy_hook(trainer, hook_name, *args, **kwargs)
>     284     return None
>     286 with trainer.profiler.profile(f"[Strategy]{trainer.strategy.__class__.__name__}.{hook_name}"):
> --> 287     output = fn(*args, **kwargs)
>     289 # restore current_fx when nested context
>     290 pl_module._current_fx_name = prev_fx_name
> 
> File ~/Pycharm_projects/paretos-demand/.venv_test/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py:367, in Strategy.training_step(self, *args, **kwargs)
>     365 with self.precision_plugin.train_step_context():
>     366     assert isinstance(self.model, TrainingStep)
> --> 367     return self.model.training_step(*args, **kwargs)
> 
> File ~/Pycharm_projects/paretos-demand/.venv_test/lib/python3.9/site-packages/neuralforecast/common/_base_windows.py:424, in BaseWindows.training_step(self, batch, batch_idx)
>     420     _, y_loc, y_scale = self._inv_normalization(
>     421         y_hat=outsample_y, temporal_cols=batch["temporal_cols"]
>     422     )
>     423     outsample_y = original_outsample_y
> --> 424     distr_args = self.loss.scale_decouple(
>     425         output=output, loc=y_loc, scale=y_scale
>     426     )
>     427     loss = self.loss(y=outsample_y, distr_args=distr_args, mask=outsample_mask)
>     428 else:
> 
> File ~/Pycharm_projects/paretos-demand/.venv_test/lib/python3.9/site-packages/neuralforecast/losses/pytorch.py:897, in poisson_scale_decouple(output, loc, scale)
>     895 rate = output[0]
>     896 if (loc is not None) and (scale is not None):
> --> 897     rate = (rate * scale) + loc
>     898 rate = F.softplus(rate) + eps
>     899 return (rate,)
> 
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Versions / Dependencies

python: Python 3.9.16
libs: neuralforecast 1.5.0
os: TUXEDO OS 2

### Reproduction script

import pandas as pd
from datasetsforecast.m5 import M5
import numpy as np

Y_df, _, _ = M5.load(directory='./', cache=True)
Y_df['ds'] = pd.to_datetime(Y_df['ds'])
Y_df = Y_df.query('unique_id.str.startswith("FOODS_3")')
Y_df['unique_id'] = Y_df['unique_id'].astype(str)
Y_df = Y_df.reset_index(drop=True)

nf = NeuralForecast(
    models=[
        AutoNHITS(h=28,loss=DistributionLoss(distribution='Poisson', level=[80, 90], return_params=False), num_samples=5),
        AutoTFT(h=28, loss=DistributionLoss(distribution='Poisson', level=[80, 90], return_params=False), num_samples=2), 
    ],
    freq='D'
)
nf = NeuralForecast(models=models, freq='D')
nf.fit(df=Y_df)

### Issue Severity

High: It blocks me from completing my task.

**Comment by kdgutier** [comment]
Hi @RobertHaase,

Thanks for reporting the bug. I believe we solved it in the main branch:
`!pip install git+https://github.com/Nixtla/neuralforecast.git`

We will update the installation instructions.

**Comment by RobertHaase** [comment]
Yes, it solves the bug!

This bug report can be closed then. Thanks for your help!

**Comment by kdgutier** [comment]
Hey @RobertHaase,

You must also add a minimal comment to the last forecast parse line.
```
# cv_df.columns = cv_df.columns.str.replace('-median', '')
```

The correctly running tutorial is already in the main branch.
https://github.com/Nixtla/neuralforecast/blob/main/nbs/examples/IntermittentData.ipynb
