### ISSUE TITLE
Is it possible to make forecast for N steps ?

### ISSUE THREAD

**Issue by beshtim** [Nixtla/neuralforecast#678]
Hi, is it possible to train a model with horizon = N, but predict with different intervals?

**Comment by 943fansi** [comment]
@beshtim Hi, you can look this example. https://github.com/Nixtla/neuralforecast/blob/main/nbs/examples/LongHorizon_Probabilistic.ipynb
In `AutoNHITS(h=horizon,
                    loss=DistributionLoss(distribution='StudentT', level=[80, 90]), 
                    config=nhits_config,
                    num_samples=5)`, you can change `h` and  `level`.

**Comment by kdgutier** [comment]
Thanks for the pointer @943fansi .

@beshtim, you can aim for different horizons through the initialization parameter `h` available in all the neural networks.

**Comment by tibeler** [comment]
i want to know how the program produce the number of horizon prediction? in a autoregressive way ?or just produce horizon results in one step?

**Comment by elephaint** [comment]
@tibeler That depends on the model. Some models do direct forecasting, others are autoregressive.

**Comment by tibeler** [comment]
Thank you ! as a beginer ,may i suggest that it would be a great idea to illustrate it in the docs?  thank you for your great work again!
