### ISSUE TITLE
[Bug] Transfer learning tutorial notebook from Nixtla/transfer-learning-time-series/ not working

### ISSUE THREAD

**Issue by williamodinsson** [Nixtla/neuralforecast#680]
I m trying to test it out the transfer learning for time series based on your page: 
https://github.com/Nixtla/transfer-learning-time-series/blob/main/nbs/Transfer_Learning.ipynb
but, when I am trying to import necessary libraries, it keeps saying : 'ModuleNotFoundError: No module named 'neuralforecast.data'', even though, I have installed all required dependencies. Any suggestion on how to fix it? 
Many thanks

**Comment by kdgutier** [comment]
Hey @williamodinsson, 

Thanks for reporting the bug. We moved the datasets from NeuralForecast into DatasetsForecast.

This is the updated/working tutorial:
https://nixtla.github.io/neuralforecast/examples/transfer_learning.html

**Comment by williamodinsson** [comment]
Thank you for your speedy response. It works now!
