### ISSUE TITLE
v1.6.0 conda package is broken

### ISSUE THREAD

**Issue by candalfigomoro** [Nixtla/neuralforecast#695]
### What happened + What you expected to happen

See: https://github.com/conda-forge/neuralforecast-feedstock/issues/14

### Versions / Dependencies

neuralforecast-1.6.0-pyhd8ed1ab_0.conda

### Reproduction script

N/A

### Issue Severity

None

**Comment by FedericoGarza** [comment]
Hey @candalfigomoro.

Thank you for letting us know about this issue. 
We've updated the conda repository [here](https://github.com/conda-forge/neuralforecast-feedstock/pull/15).
Once it is merged, it should be available in a couple of hours.﻿

**Comment by FedericoGarza** [comment]
Hey! The new version is already in conda.
Let us know if the problem persists. :)﻿
