### ISSUE TITLE
How to interpret the trained model?

### ISSUE THREAD

**Issue by landkwon94** [Nixtla/neuralforecast#698]
### Description

Hello Sir! 

First of all, thank you so much for sharing your amazing codes!

I am using TFT model for train/validate/test for time-series forecasting.

After training the model, I want to visualize 'feature importance' and 'attention weights' such as figures below (from the original paper)

![image](https://github.com/Nixtla/neuralforecast/assets/73383617/9e4ab5d2-8c47-45d6-8476-7c20e4008008)

![image](https://github.com/Nixtla/neuralforecast/assets/73383617/1c433940-b3af-4d9e-8bb5-1bf94cc925a4)

Is there any module we can use to perform this visualization in neuralforecast? 

I will wait for your reply!

Many thanks for your contributions :)

**Comment by marcopeix** [comment]
#1104 solves this issue.
