### ISSUE TITLE
[AutoLSTM] Error in get hyperparameter tuning

### ISSUE THREAD

**Issue by guisef** [Nixtla/neuralforecast#710]
### What happened + What you expected to happen

After fit the model, I tried get hyperparameter tuning results, but this error appears: 
" results = model.results.get_dataframe()
AttributeError: 'list' object has no attribute 'results' "
I am following the steps that are in this link: https://nixtla.github.io/neuralforecast/examples/automatic_hyperparameter_tuning.html.
Am I doing something wrong? 

### Versions / Dependencies

Neuralforecast - version 1.6.1

### Reproduction script

model = [AutoLSTM(h=h,
                    num_samples=30,
                    loss= WMAPE())]

nf = NeuralForecast(models=model, freq='M')
fit = nf.fit(train, val_size=30)
results = model.results.get_dataframe()

### Issue Severity

Low: It annoys or frustrates me.

**Comment by cchallu** [comment]
Hi @guisef! The `model` is a list, so you need to index it to extract the results. Or alternatively you can use the `models` attribute of `nf`. The line is  `results = nf.models[0].results.get_dataframe()`

**Comment by guisef** [comment]
Thank you!
I could get my results.
