### ISSUE TITLE
[Model|Loss] Device error with DistributionLoss on GPU

### ISSUE THREAD

**Issue by Antoine-Schwartz** [Nixtla/neuralforecast#711]
### What happened + What you expected to happen

If the input data is not scaled (i.e.: `scaler="identity" or None`) and if the model is fit with a `DistributionLoss` on a GPU, we end up with a device error when predicting:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`.

This is the case, for example, when you call DeepAR with its default values!

It's the same kind of error fixed a few days ago in this PR https://github.com/Nixtla/neuralforecast/pull/706.

### Versions / Dependencies

neuralforecast==1.6.1

### Reproduction script

```
from neuralforecast import NeuralForecast
from neuralforecast.models import DeepAR
from neuralforecast.utils import AirPassengersPanel

Y_df = AirPassengersPanel

nf = NeuralForecast(
    models=[DeepAR(
        h=12,
        input_size=48,
        max_steps=100,
        accelerator="gpu"
        ),
    ],
    freq='M'
)
nf.fit(Y_df)
Y_hat_df = nf.predict()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by winedarksea** [comment]
I've seen this bug too.

I have even fixed it locally by fixing approximately line 720 of the pytorch.py file of the Oct 5th release by changing it to this:


```python
def normal_scale_decouple(output, loc=None, scale=None, eps: float = 0.2):
    """Normal Scale Decouple

    Stabilizes model's output optimization, by learning residual
    variance and residual location based on anchoring `loc`, `scale`.
    Also adds Normal domain protection to the distribution parameters.
    """
    mean, std = output
    std = F.softplus(std)
    if (loc is not None) and (scale is not None):
        mean = (mean.to('cuda') * scale.to('cuda')) + loc.to('cuda')
        std = (std.to('cuda') + eps) * scale.to('cuda')
    return (mean, std)
```
the problem with this fix is that the hardcoded .to('cuda') would probably break cpu training and it is unclear how I could fix this without a decent rework of the code (passing 'devices' into the function, maybe)

**Comment by jmoralez** [comment]
This was fixed for DeepAR in #761. Have you run into this with a different model?

**Comment by winedarksea** [comment]
I think this error was occurring on all models that used that distribution loss but I haven't checked again explicitly. This was on Version: 1.6.4 which landed October 2023, after that merge.
Error only occurred on GPU, if using a CPU only install it should work

**Comment by Antoine-Schwartz** [comment]
Hello, I no longer had a problem on the 1.6.4, it’s solved, thank you!
