### ISSUE TITLE
Error in probabilistic forecast/uncertainty intervals tutorial

### ISSUE THREAD

**Issue by SoulMUSZE** [Nixtla/neuralforecast#713]
I'm trying to run the probabilistic forecast tutorial below:
https://nixtla.github.io/neuralforecast/examples/uncertaintyintervals.html

But I'm getting the following error when trying to fit the training data into the models:

RuntimeError                              Traceback (most recent call last)
[<ipython-input-14-0827025e27d6>](https://localhost:8080/#) in <cell line: 1>()
----> 1 nf.fit(df=Y_train_df)

30 frames
[/usr/local/lib/python3.10/dist-packages/neuralforecast/losses/pytorch.py](https://localhost:8080/#) in _weighted_mean(losses, weights)
     33     Compute weighted mean of losses per datapoint.
     34     """
---> 35     return _divide_no_nan(torch.sum(losses * weights), torch.sum(weights))
     36 
     37 # %% ../../nbs/losses.pytorch.ipynb 7

RuntimeError: The size of tensor a (5) must match the size of tensor b (700) at non-singleton dimension 2

**Comment by cchallu** [comment]
Hi @SoulMUSZE. Thanks for finding the error. We recently introduced a new feature (`horizon_weights`) in the library that is causing the error. I will take a look at this and fix it.

**Comment by cchallu** [comment]
Hi @SoulMUSZE! We just fixed this issue in the latest PR. It will be in the main branch and pip version in the next hours. Sorry for the delay!
