### ISSUE TITLE
step_size modulo check complicates predict_insample() with step_size > 1

### ISSUE THREAD

**Issue by tg2k** [Nixtla/neuralforecast#714]
### What happened + What you expected to happen

What's the purpose of the ```"`test_size - h` should be module `step_size`"``` check at https://github.com/Nixtla/neuralforecast/blob/7df60ac233820e87920c599cfd53ed1ea6956f93/neuralforecast/core.py#L41C1-L42C72 (and https://github.com/Nixtla/neuralforecast/blob/7df60ac233820e87920c599cfd53ed1ea6956f93/neuralforecast/core.py#L441C1-L442C80 ) ? It complicates running `predict_insample` with a `step_size` > 1. I checked the history and this was part of a big commit replacing all or most of the repo's files on 3 Oct 2022. If I remove the check (the first check, specifically), I don't notice downstream problems, but I haven't done exhaustive testing.

I've included repro code demonstrating the issue. Note that I had additional issues in making the repro:

1. `Error: No available node types can fulfill resource request {'GPU': 1.0}. Add suitable node types to this cluster to resolve this issue.` -- I'm running on WSL 2 and I verified that torch can see the GPUs. The `ray.init(num_cpus=12, num_gpus=1)` line resolved this. I believe looking at https://github.com/ray-project/ray/issues/13905 helped.

1. During the training process I get a lot of errors of the general form `RuntimeError: maximum size for tensor at dimension 2 is 240 but size is 253`. Training still completes but it's unclear to me whether this is a serious problem. I have checked https://github.com/Nixtla/neuralforecast/issues/563 and https://github.com/Nixtla/neuralforecast/issues/566 and this repro isn't using exogenous data. In any case training continues, but it's unclear how to look at this error and whether it can be completely resolved.

### Versions / Dependencies

Windows 11; WSL 2 (Ubuntu); neuralforecast 1.6.1; Python 3.10; others per https://github.com/Nixtla/neuralforecast/blob/main/environment.yml

### Reproduction script

```
# based on https://nixtla.github.io/neuralforecast/examples/getting_started_complete.html
import pandas as pd

Y_df = pd.read_parquet('https://datasets-nixtla.s3.amazonaws.com/m4-hourly.parquet')

max_len = 10 * 24
Y_df = Y_df.groupby('unique_id').tail(10 * 24) #Select last 10 days of data to make example faster
# ensure ds ends at the same point, avoid errors in cv
Y_df['ds'] = Y_df.groupby('unique_id')['ds'].transform(lambda x: range(len(x) - max_len + 1, max_len + 1))

# This was needed for my configuration to prevent
# "Error: No available node types can fulfill resource request {'GPU': 1.0}. Add suitable node types to this cluster to resolve this issue."
import ray
ray.init(num_cpus=12, num_gpus=1)

from ray import tune

from neuralforecast import NeuralForecast
from neuralforecast.auto import AutoNHITS
from neuralforecast.losses.pytorch import MQLoss

config_nhits = {
    "input_size": tune.choice([48, 48*2, 48*3, 48*5]),              # Length of input window
    "n_blocks": 5*[1],                                              # Length of input window
    "mlp_units": 5 * [[64, 64]],                                  # Length of input window
    "n_pool_kernel_size": tune.choice([5*[1], 5*[2], 5*[4],         
                                      [8, 4, 2, 1, 1]]),            # MaxPooling Kernel size
    "n_freq_downsample": tune.choice([[8, 4, 2, 1, 1],
                                      [1, 1, 1, 1, 1]]),            # Interpolation expressivity ratios
    "learning_rate": tune.loguniform(1e-4, 1e-2),                   # Initial Learning rate
    "scaler_type": tune.choice([None]),                             # Scaler type
    "max_steps": tune.choice([10]),                               # Max number of training iterations (debugging)
    "batch_size": tune.choice([32, 64, 128, 256]),                  # Number of series in batch
    "windows_batch_size": tune.choice([128, 256, 512, 1024]),       # Number of windows in batch
    "random_seed": tune.randint(1, 20),                             # Random seed
}

horizon = 13
# count the unique number of values and ensure it is not divisible by horizon to reproduce exception
df_rows = len(Y_df['ds'].unique())
assert df_rows % horizon != 0

nf = NeuralForecast(
    models=[
        AutoNHITS(h=horizon, config=config_nhits, loss=MQLoss(), num_samples=5),
    ],
    freq='H'
)

nf.fit(df=Y_df)
print("Done fitting, predicting...")

Y_hat_insample = nf.predict_insample(step_size=horizon)  # "`test_size - h` should be module `step_size`" exception occurs here

Y_hat_insample.columns = Y_hat_insample.columns.str.replace('-median', '')

# filter to only the target column
target_column = 'H1'
Y_hat_insample_target = Y_hat_insample[Y_hat_insample['unique_id'] == target_column]

# based on https://nixtla.github.io/neuralforecast/examples/predictinsample.html#plot-predictions
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.plot(Y_hat_insample_target['ds'], Y_hat_insample_target['y'], label='True')
plt.plot(Y_hat_insample_target['ds'], Y_hat_insample_target['AutoNHITS'], label='Forecast')
plt.xlabel('Timestamp [t]')
plt.ylabel('Value')
plt.grid()
plt.legend()
plt.show(block=True)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by cchallu** [comment]
Hi @tg2k!

1)The error:

```RuntimeError: maximum size for tensor at dimension 2 is 240 but size is 253```

was just fixed in a recent PR with additional padding. This is usually caused by having short time series, shorter than `input_size+h`. While it won't raise errors anymore, it is recommended to have `input_size+h << length`, so that the model can observe multiple windows per time series during training.

2) The check: ```"`test_size - h` should be module `step_size`"``` is important to return forecasts of the correct dimensions. If this check is removed, the last forecast window will go beyond the actual data (for in-sample or historic forecasts, this is problematic). The easiest solution is to trim the historic data to satisfy this requirement.

**Comment by tg2k** [comment]
Thanks @cchallu . I'm not sure in this case if I had short time series in the tests with the `maximum size for tensor issue`. I since discovered that I would also see this issue with cross-validation if `input_size` (probably `input_size + h` as you say) was large enough that, when setting `n_windows`, it would cause overlapping cross-validation windows. Once I moved to automatically computing `n_windows` the problems went away. When using the Auto versions of models, to avoid the error on any model I had to take the max `input_size` into account.

Applying the advice to trim the historic data meant I could safely restore the ```"`test_size - h` should be module `step_size`"``` check that I'd hacked out for testing.

**Comment by ZucchiniAI** [comment]
Hi, I am using version 1.6.2 and encounter the same problem" with `test_size - h` should be module `step_size`": perhaps I do not understand fully the meaning:
I have test_size=60 , h= 30 and step_size=30 --> that shall satisfy the request, right? but I get the same the error. 
Can I still use a val_size at the same time as parameter in the fit method?
Thank you !
