### ISSUE TITLE
AutoNHITS default config Creates Invalid Configurations

### ISSUE THREAD

**Issue by james-rekow-kinsa** [Nixtla/neuralforecast#716]
The default config here:

{'input_size_multiplier': [1, 2, 3, 4, 5],
 'h': None,
 'n_pool_kernel_size': <ray.tune.search.sample.Categorical at 0x7e0a7ae203d0>,
 'n_freq_downsample': <ray.tune.search.sample.Categorical at 0x7e0a7ae20490>,
 'learning_rate': <ray.tune.search.sample.Float at 0x7e0a7ae204f0>,
 'scaler_type': <ray.tune.search.sample.Categorical at 0x7e0a7ae205b0>,
 'max_steps': <ray.tune.search.sample.Float at 0x7e0a7ae20550>,
 'batch_size': <ray.tune.search.sample.Float at 0x7e0a7ae20790>,
 'windows_batch_size': <ray.tune.search.sample.Float at 0x7e0a7ae208b0>,
 'loss': None,
 'random_seed': <ray.tune.search.sample.Integer at 0x7e0a7ae20970>}

uses Floats for batch_size, which must be an int. This causes this error:

ValueError: batch_size should be a positive integer value, but got batch_size=8.396435675503097 (or other float val).

**Comment by cchallu** [comment]
Hi @james-rekow-kinsa . Sorry for the late reply; we fixed this issue in the latest version.
