### ISSUE TITLE
transfer learning process were wrong!!!

### ISSUE THREAD

**Issue by ZhikangLai** [Nixtla/neuralforecast#724]
Your transfer learning process were wrong. You didn't retrain the pre trained model after importing it.

**Comment by cchallu** [comment]
Hi @ZhikangLai, what transfer learning process are you referring to?

**Comment by Arnechos** [comment]
Hello @cchallu 
I'm playing around with the library  with transfer learning problem and I think @ZhikangLai was reffering to the notebook/example - Transfer_Learning.ipynb
This is the Table of Contents:

- Installing NeuralForecast/DatasetsForecast
- Load M4 Data
- Instantiate NeuralForecast core, Fit, and save
- Load pre-trained model and predict on AirPassengers
- Evaluate Results

What's missing is a case when you take the M4 trained model and re-fit on AirPassengers. As I understand all I would have to do is take that saved model, load, fit to AirPassengers train dataset and the predict on test the same way Pytorch lightning works, right?

**Comment by willadamskeane** [comment]
@cchallu I'm also wondering if that's the expected workflow. If I want to predict on a new dataset (w/ different time series id's), I should fit and then predict?
