### ISSUE TITLE
Calling Predict with exogenous var. causes wrong/time shifted prediction

### ISSUE THREAD

**Issue by StefanWiegandSSW** [Nixtla/neuralforecast#727]
### What happened + What you expected to happen

Training NHITs on AirPassengersDF, once with only y and once additionally with the month as exogenous variable, results in very different prediction results.
When I train a model with exogenous variables and call predict on it, the result is obviously time shifted. I guess the exogenous variable from the training df is used not the futr_df I provided. As they correspond to different time steps in the season the shift becomes visible. (df starting with month=1, futr_df starting with month=8)
Trained and Predicted only on y:
![image](https://github.com/Nixtla/neuralforecast/assets/142790101/b1ef23c8-28f1-4768-a7e5-d78c6e94c1b5)

Trained and Predicted only on y and month:
![image](https://github.com/Nixtla/neuralforecast/assets/142790101/97b121ea-93ca-40c1-9076-808298c48af4)

### Versions / Dependencies

Regular Colab 

### Reproduction script

```python
# predict_is_lagged

# %%capture
# !pip install neuralforecast

from neuralforecast.utils import AirPassengersDF
import pandas as pd

df_all = AirPassengersDF
# Extract the month from the 'ds' column and add it as a new column
df_all['ds'] = pd.to_datetime(df_all['ds'])
df_all['month'] = df_all['ds'].dt.month

df_all#.head()

# split in training and test data sets
# Sort the DataFrame by the 'ds' column
df_all = df_all.sort_values(by='ds')

# Calculate the number of rows for each new DataFrame
n_rows = len(df_all)
n_future = 29
n_train = n_rows - n_future

# Split the DataFrame into three separate DataFrames
df_train = df_all.iloc[:n_train]
df_future = df_all.iloc[n_train:]

# Display the resulting DataFrames
print(df_train)
print(df_future)

from neuralforecast.auto import NHITS, AutoNHITS
from neuralforecast.core import NeuralForecast
horizon = 12
models = [NHITS(h = horizon,
                input_size = 5*horizon,
                mlp_units = 3 * [[64, 64]],
                max_steps=100,
                futr_exog_list = ["month"] # comment to try without
              )
          ]


# %%capture
nf = NeuralForecast(models=models, freq='M')
nf.fit(df=df_train, val_size=24)

Y_hat_df = nf.predict(futr_df=df_future) # remove call args to try without
Y_hat_df = Y_hat_df.reset_index()
Y_hat_df.head()

# Finally, we plot the original time series and the forecasts.

import pandas as pd
import matplotlib.pyplot as plt

Y_hat_df

import matplotlib.pyplot as plt

plot_df_past = df_train.tail(horizon*4).reset_index(drop=True)
merged_df = pd.merge(df_all, Y_hat_df, on='ds', how='inner')
plot_df = pd.concat([plot_df_past, merged_df]).set_index('ds') # Concatenate the train and forecast dataframes

plot_df[['y', 'NHITS']].plot(linewidth=2)
plt.ylabel('Monthly Passengers', fontsize=20)
plt.xlabel('Timestamp [t]', fontsize=20)
plt.legend(prop={'size': 15})
plt.grid()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by cchallu** [comment]
Hi @StefanWiegandSSW!

I replicated your example. The problem arises because your `df_future` has 29 rows, but the forecast horizon of the model is 12. **The length of `df_future` should match the horizon of the model**.

In your example, the model is forecasting the last 12 rows of `df_future` but because it has 29 rows, it is shifted by 17 datestamps.

We will add an assert in the `predict` method to only allow for `futr_df` dataframes that match the forecast horizon.

**Comment by StefanWiegandSSW** [comment]
Thanks for the explanation!
