### ISSUE TITLE
Problema al proyectar

### ISSUE THREAD

**Issue by AlineLPL** [Nixtla/neuralforecast#746]
Hola, 

Me surgió un tema al proyectar la información, cuando uso la sentencia:
Y_hat_df = nf.predict(futr_df=h)
Y_hat_df.head()

me arroja el siguiente error:
ValueError: `futr_df` must have one row per id and ds in the forecasting horizon (20).

Pero mi dataframe solo tiene un id para cada fecha, no se repiten, es la primera vez que me pasa, ¿hay alguna actualización que deba considerar ?

De antemano muchas gracias.

**Comment by jmoralez** [comment]
Hola. Eso puede pasar si `futr_df` tiene menos fechas que tu horizon (20 en este caso). Si tienes 10 ids tu futr_df debería tener 200 renglones (n_ids * h), puedes revisar eso?

**Comment by AlineLPL** [comment]
Si coincide, tengo 6,062 ids, quiero proyectar 20 días y mi dataframe tiene 121,240 registros, no tengo duplicados, ¿este error podría pasar por algo más ?

**Comment by jmoralez** [comment]
Las fechas deben estar en el futuro, es decir, empezar un período después de las fechas en train.

**Comment by AlineLPL** [comment]
Mi última fecha de train 2023-09-07 y mi set para proyectar empieza en 2023-09-08

**Comment by AlineLPL** [comment]
Son días saltados los que le paso en mi dataframe, pero siempre se los había pasado así, es decir los siguientes 20 días solo son hábiles, pero hasta el momento no había tenido tema en proyectarlo de esa manera, ¿eso cambio?

**Comment by jmoralez** [comment]
Sí, agregamos validaciones para asegurarnos que el futr_df es correcto. Si cambias las fechas a días naturales debe funcionar.

**Comment by AlineLPL** [comment]
en efecto tuve que meter los días faltantes, pero por ejemplo yo solo proyecto comportamientos en días hábiles por eso generaba un dataframe únicamente con fechas futuras de mi interés que tenían ciertos comportamiento cíclicos , en mis variables exógenas solo hay info en esos días, los fines de semana los mandé en cero, ¿ la salida no debería proyectar las fechas que yo le de y no dármelo diario ?, en realidad las proyecciones de esos días no son relevantes, o en realidad no esta tomando en cuanta los factores cíclicos que le mando?

**Comment by jmoralez** [comment]
Las fechas futuras se construyen tomando la última fecha de entrenamiento y agregando la frecuencia que utilizaste. Si solo los días hábiles son de interés creo que podrías usar `freq='B'` en lugar de `freq='D'` y pasar el dataframe futuro con las fechas de días hábiles como lo hacías antes.
