### ISSUE TITLE
BaseRecurrent `available_ts` off by 1

### ISSUE THREAD

**Issue by KeAWang** [Nixtla/neuralforecast#752]
### What happened + What you expected to happen

`available_ts` in `BaseRecurrent` is off by one, as seen here: https://github.com/Nixtla/neuralforecast/blob/e56f4428e29f2804ce47f07a93d87d1b152e58d2/neuralforecast/common/_base_recurrent.py#L247

For example, if `temporal` has 100 timesteps (`temporal.shape[-1] == 100`), and none of them are masked (`min_time_stamp == 0`), then `available_ts` would equal 101 available timestamps, which is not correct.

### Versions / Dependencies

neuralforecast 1.6.3

### Reproduction script

N/A

### Issue Severity

Low: It annoys or frustrates me.

**Comment by cchallu** [comment]
Hi @KeAWang. Thanks for revising our code in such detail! You are correct; it should not have the + 1.

Let me know if you are interested in fixing the issue yourself in a new PR and becoming a contributor. Here is the contributing guide: https://github.com/Nixtla/neuralforecast/blob/main/CONTRIBUTING.md (one step missing in the guide is that all changes should be done in your fork).

**Comment by KeAWang** [comment]
Happy to contribute!
