### ISSUE TITLE
Problem recalled in model.dataset

### ISSUE THREAD

**Issue by mjko0916** [Nixtla/neuralforecast#753]
### What happened + What you expected to happen

When I load saved model.dataset, Error massage **"'TimeseriesDataset' object has no attribute 'data'"** occurs.
It seems to be caused in tsdataset.py, __repr__  function.
```
def __repr__(self):
        return (
            f"TimeSeriesDataset(n_data={self.data.size:,}, n_groups={self.n_groups:,})"
        )
```

### Versions / Dependencies

1.6.1

### Reproduction script

```
def __repr__(self):
        return (
            f"TimeSeriesDataset(n_data={self.indptr.size:,}, n_groups={self.n_groups:,})"
        )

```

### Issue Severity

None

**Comment by jmoralez** [comment]
Fixed in #754
