### ISSUE TITLE
valid_loss is abnormal

### ISSUE THREAD

**Issue by Houyikai** [Nixtla/neuralforecast#755]
### What happened + What you expected to happen

![image](https://github.com/Nixtla/neuralforecast/assets/39182537/86e2f99e-3964-4d4a-83ba-b81d01d7c15f)

the valid_loss is abnormal

### Versions / Dependencies

nothing

### Reproduction script

nf = NeuralForecast(models=[nhits], freq=freq)
Y_hat_insample = nf.cross_validation(df=Y_df, val_size=val_size, test_size=test_size, n_windows=None)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by cchallu** [comment]
Hi @Houyikai. The validation loss is scaled back to the original scale of the data since it's used for model selection and early stopping. The train loss its computed on the scaled values based on the `scaler_type`.

**Comment by Houyikai** [comment]
> Hi @Houyikai. The validation loss is scaled back to the original scale of the data since it's used for model selection and early stopping. The train loss its computed on the scaled values based on the `scaler_type`.

ok thanks

**Comment by Houyikai** [comment]
@cchallu ，boss，base mthod has no test_step，is there any way i can do test without implementing a test method, cause i see there‘s a windows_batch kind thing  which i dont understand.  i know that corss validation return's a comparison set ,but its just too big. big thanks

**Comment by Houyikai** [comment]
answered
