### ISSUE TITLE
Informer and MAE() not imported in the example usage shown for informer.

### ISSUE THREAD

**Issue by nelson123-lab** [Nixtla/neuralforecast#764]
The example usgae provided in this page of informer [Informer](https://nixtla.github.io/neuralforecast/models.informer.html)
the informer and the MAE() are not imported it is not working without importing them. I suggest you add that along with the other imports.

from neuralforecast.models import Informer
from sklearn.metrics import mean_absolute_error as MAE

**Comment by cchallu** [comment]
Hi @nelson123-lab. Thanks for finding this issue. Yes, MAE should be imported if specified, but note that it has to be the module from our library, in `losses.pytorch`.

**Comment by cchallu** [comment]
We also recommend this full example: https://nixtla.github.io/neuralforecast/examples/longhorizon_with_transformers.html
