### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'backend'

### ISSUE THREAD

**Issue by luoolu** [Nixtla/neuralforecast#771]
### TypeError: __init__() got an unexpected keyword argument 'backend'

AutoNHITS
TypeError: __init__() got an unexpected keyword argument 'backend'

### Versions / Dependencies

latest release version

### Reproduction script

models = [AutoNHITS(h=1,
                        loss=MAE(),
                        config=config_nhits,
                        search_alg=optuna.samplers.TPESampler(),
                        backend='optuna',
                        verbose=True,
                        num_samples=10)]

### Issue Severity

High: It blocks me from completing my task.

**Comment by cchallu** [comment]
Hi @luoolu. We did the release with the `backend` parameteron pip today; it should be fixed in the latest version.

**Comment by luoolu** [comment]
thanks
