### ISSUE TITLE
No windows available for training

### ISSUE THREAD

**Issue by wsfzghnr** [Nixtla/neuralforecast#787]
### What happened + What you expected to happen

While attempting to train a model on my dataset, I encountered an exception stating that the time series is too short for training. The exact error message is: Exception: Time series is too short for training, consider setting a smaller input size or set start_padding_enabled=True.
When I change the input size, the error became No windows available for training

### Versions / Dependencies

Exception: No windows available for training

### Reproduction script

Exception: No windows available for training

### Issue Severity

High: It blocks me from completing my task.

**Comment by cchallu** [comment]
Hi @wsfzghnr. Can you provide more details on your task? For instance, the model, input_size, output_size, and time series length.
