### ISSUE TITLE
Hyperlink(s) Broken

### ISSUE THREAD

**Issue by NavidGhorbanali** [Nixtla/neuralforecast#788]
The Hyperlink to the losses collection and model collection in the docs are inoperable. Obviously its not too hard to find them, but its a quality of life thing. For example, on this page :

![image](https://github.com/Nixtla/neuralforecast/assets/119272532/842701c5-a1c5-4e24-8194-f4852ca59a86)

**Comment by marcopeix** [comment]
Link works for both auto and non-auto models. Closing for now.
