### ISSUE TITLE
neuralforecast predict error msg: must have one row per id and ds in the forecasting horizon

### ISSUE THREAD

**Issue by studiocardo** [Nixtla/neuralforecast#789]
### What happened + What you expected to happen

I'm using AutoNHITS to train a predictor for my time series. 

```python
val_size = horizon = 48
nf = NeuralForecast(models=models, freq='D')
nf.fit(df=train, static_df=static_df, val_size=val_size)
y_hat = nf.predict(futr_df=fut)

ValueError                                Traceback (most recent call last)
Cell In[17], line 2
      1 fut['ds'] = pd.to_datetime(fut['ds'])
----> 2 y_hat = nf.predict(futr_df=fut)

File ~\anaconda3\envs\neuralforecast164\lib\site-packages\neuralforecast\core.py:369, in NeuralForecast.predict(self, df, static_df, futr_df, sort_df, verbose, **data_kwargs)
    367 base_err_msg = f"`futr_df` must have one row per id and ds in the forecasting horizon ({self.h})."
    368 if futr_df.shape[0] < fcsts_df.shape[0]:
--> 369     raise ValueError(base_err_msg)
    370 if futr_orig_rows > futr_df.shape[0]:
    371     dropped_rows = futr_orig_rows - futr_df.shape[0]

**ValueError: `futr_df` must have one row per id and ds in the forecasting horizon (48).**
```

I looked the Case #746 since it had the same error message, and I still can't figure out how to fix it.  I verified that:

1. the prediction horizon does come after the training data date.

train.ds.max() = Timestamp('2015-07-31 00:00:00')
fut.ds.min() = Timestamp('2015-08-01 00:00:00')

2. the test data does follow the one row per id and dis

Here's an example of test dataframe, fut.

unique_id	ds	Open	Promo	StateHoliday	SchoolHoliday	Week	DayofWeek	Dayofyear	WeekOfYear	Qtr	Days	DayOfMonth	Promo2	Promo2Open	Promo2InEffect
40232	1	2015-08-01	1.0	0	0	1	31	5	213	31	2	0.000000	0	0	0.0	0
39376	1	2015-08-02	0.0	0	0	1	31	6	214	31	2	0.021271	0	0	0.0	0

fut is organized by 'unique_id', and then 'ds'.  So, there is a block of 48 rows, each represents a date, that belong to a unique_id.  This structure repeats 855 for a total of 836 unique_id's.

3. training and testing data are both on the daily basis.

Any suggestion on what I might done wrong?  TIA!

### Versions / Dependencies

neuralforecat 1.6.4
python 3.9.8
optuna 3.3
wandb 0.15.12

### Reproduction script

```python
models = [AutoNHITS(h=horizon,
                    loss=MSE(),
                    config=nhits_config,
                    valid_loss=MSE(),
                    search_alg=optuna.samplers.TPESampler(),
                    backend='optuna',
                    num_samples=1, 
                    gpus=1,
                    verbose=True)]

nf = NeuralForecast(models=models, freq='D')
nf.fit(df=train, static_df=static_df, val_size=val_size)

y_hat = nf.predict(futr_df=fut)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey @studiocardo. Are you sure your `futr_df` contains all the required combinations? This error could also happen if you're missing a date, for example if your horizon is 2 and your futr_df looks like this:
| unique_id | ds | exog_1 |
| - | - | - |
| 1| 2020-01-01 | 30 |
| 1| 2020-01-03 | 20 |

Even though you have 2 samples one date is missing (2020-01-02).
You can also directly create the structure that is being used for the validation so you can take a closer look:
```python
from neuralforecast.core import _future_dates

models = [AutoNHITS(h=horizon,
                    loss=MSE(),
                    config=nhits_config,
                    valid_loss=MSE(),
                    search_alg=optuna.samplers.TPESampler(),
                    backend='optuna',
                    num_samples=1, 
                    gpus=1,
                    verbose=True)]

nf = NeuralForecast(models=models, freq='D')
nf.fit(df=train, static_df=static_df, val_size=val_size)
expected_futr_df = _future_dates(nf.dataset, nf.uids, nf.last_dates, nf.freq, nf.h)
```

**Comment by studiocardo** [comment]
Hi Jose

Thanks for your quick reply.

The unique_id are in the form of integer but they are not contiguous (almost).  But I don't think that matters since the exogenous example used strings like "FR" and "BR" for unique_id.

But I know you are talking about "ds", so I did

ds=fut.ds.value_counts()
ds.sort_index()

and I can confirm that len(ds) = 48 = horizon.  And the 48 indices are contiguous, spanning from "2015-08-01" to "2015-09-17", representing the 48 days in the prediction horizon.  And all dates contain exactly 856 unique_id's.  

ds
2015-08-01    856
2015-08-02    856
2015-08-03    856
2015-08-04    856
2015-08-05    856
2015-08-06    856
2015-08-07    856
2015-08-08    856
2015-08-09    856
2015-08-10    856
2015-08-11    856
2015-08-12    856
2015-08-13    856
2015-08-14    856
2015-08-15    856
2015-08-16    856
2015-08-17    856
2015-08-18    856
2015-08-19    856
2015-08-20    856
2015-08-21    856
2015-08-22    856
2015-08-23    856
2015-08-24    856
2015-08-25    856
2015-08-26    856
2015-08-27    856
2015-08-28    856
2015-08-29    856
2015-08-30    856
2015-08-31    856
2015-09-01    856
2015-09-02    856
2015-09-03    856
2015-09-04    856
2015-09-05    856
2015-09-06    856
2015-09-07    856
2015-09-08    856
2015-09-09    856
2015-09-10    856
2015-09-11    856
2015-09-12    856
2015-09-13    856
2015-09-14    856
2015-09-15    856
2015-09-16    856
2015-09-17    856

This, to me, says that all dates are present (thus 48) and no unique_id is missing.   The ds column has always been in datetime, but to be sure, I did

fut['ds'] = pd.to_datetime(fut['ds'])

And it made no difference.  Any suggestion where to look next?  Thx!
Stefan

**Comment by jmoralez** [comment]
You can try running the code I suggested in https://github.com/Nixtla/neuralforecast/issues/789#issuecomment-1768999330 and perform a join like the following:
```python
full = expected_futr_df.merge(fut, on=['unique_id', 'ds'], how='left')
missing = full[full[fut.columns].isnull().any(axis=1)]
```
`missing` would contain the combinations that are expected but not in `fut`.

**Comment by studiocardo** [comment]
from neuralforecast.core import _future_dates
expected_futr_df = _future_dates(nf.dataset, nf.uids, nf.last_dates, nf.freq, nf.h)
full = expected_futr_df.merge(fut, on=['unique_id', 'ds'], how='left')
missing = full[full[fut.columns].isnull().any(axis=1)]

And guess what?  It's the non-contiguous unique_id's that are in missing.  I did mention the fact that the unique_id are in fact not contiguous, but that wasn't our focus.

<html>
<body>


2 | 2015-08-01 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
2 | 2015-08-02 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
2 | 2015-08-03 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
2 | 2015-08-04 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
2 | 2015-08-05 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
1110 | 2015-09-13 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
1110 | 2015-09-14 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
1110 | 2015-09-15 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
1110 | 2015-09-16 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN | NaN | NaN
1110 | 2015-09-17 | NaN | NaN | NaN | NaN | NaN | NaN | NaN | <NA> | NaN | NaN | NaN | NaN

<br class="Apple-interchange-newline">
</body>
</html>

missing.unique_id.value_counts()

unique_id
2       48
841     48
730     48
735     48
743     48
        ..
396     48
400     48
401     48
402     48
1110    48
Name: count, Length: 259, dtype: int64

There are 1115 unique_id's in the training data and only 856 in the test data.  So the test data indeed do not have all the unique_id's found in training data.  But what does that mean?  And on what basis does expected_futr_df define what must be in the test data?  So because the test data do not contain all the unique_id's from train, it's going to reject the data?  Or is it expecting a contiguous series of data?  If the latter were the case, then why was the exogenous example able to proceed with ['FR', 'BR'] as unique_id?  This is a quite unexpected twist, please advise how to proceed. 

Many thanks for your help.

Stefan

**Comment by jmoralez** [comment]
Sorry I thought you meant the ids weren't encoded as consecutive, not that there were less than during training. In that case you need to provide the full df to the predict method:
```python
nf.predict(df=train[train['unique_id'].isin(fut['unique_id'])], futr_df=fut)
```

**Comment by studiocardo** [comment]
Hi Jose

Ok, great, so the moral of the story is that unique_id's do not have to be consecutive, they could be [Mary, Paul, Joseph, 50cents, 101]; it ain't gonna matter.  What matters is that the predicting tasks needs to have the model present ONLY the unique_id's that are used in futr_df.  

Oh, by the way, shouldn't the prediction in the [exogenous variable example](https://nixtla.github.io/neuralforecast/examples/exogenous_variables.html) be

Y_hat_df = nf.predict(futr_df=futr_df, static_df=static_df) 

Thanks for your help!
Stefan

**Comment by jmoralez** [comment]
Closing since people won't run into this anymore with #833

**Comment by rafaepires** [comment]
I have same problem: ValueError: `futr_df` must have one row per id and ds in the forecasting horizon (3).
Did anyone solve this problem?
