### ISSUE TITLE
Supplying a non-existing column in exogenous features list leads to unexpected results 

### ISSUE THREAD

**Issue by nulam** [Nixtla/neuralforecast#790]
https://github.com/Nixtla/neuralforecast/blob/b7ab0a607022476e6bd9eb69557185dd61862057/neuralforecast/common/_base_windows.py#L419

We encountered a nasty bug where a typo in the name of a historical exogenous column didn't throw an error and also had an influence on the model's observed performance. We believe the culprit is in the code referenced above, where the get_indexer function returns -1 index on keys which were not found, which in turn defaults to the last column in the dataframe (possibly leading to unindented information leakage). 

Suggested fix: verify the column names provided by the user are present in the dataframe during initial preprocessing

**Comment by cchallu** [comment]
Hi @nulam . Thanks for the issue! We recently added a protection that checks that all variables in the `hist_exog_list` are in the input dataframe. Are you using the last version? We will also double-check that the protection is working.
