### ISSUE TITLE
Exogenous variables on AutoNBEATSx

### ISSUE THREAD

**Issue by Yasslight90** [Nixtla/neuralforecast#791]
Hello,

To pass exogenous variables to NBEATSx, there are three attributes ( futr_exog_list, hist_exog_list and stat_exog_list). I can't however find these attributes in AutoNBEATSx. How can we pass exogenous variables to it ?

Thanks 

Yass

### Versions / Dependencies

neuralforecast  1.6.4

### Reproduction script

config = dict(input_size=24)
models = [AutoNBEATSx(h=12, cpus=4, config = config)]
nf = NeuralForecast(models=models, freq='MS')
nf.fit(df=df, static_df=static_df)
Y_hat_df = nf.predict(futr_df=futr_df)

where can I pass the exogenous variables ?

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey. You can provide them in the config, e.g. `config = dict(input_size=24, futr_exog_list=['x1'])`.
