### ISSUE TITLE
GRU encoder_activation

### ISSUE THREAD

**Issue by juliana-yc-han** [Nixtla/neuralforecast#796]
Hi,

I've encountered an issue when using the GRU class from NeuralForecast. Specifically, I observed that the results are identical when setting the encoder_activation parameter to 'relu' as compared to the default 'tanh'.

Here's a brief overview of the setup I used:
model1 = GRU(h, encoder_activation='relu')
model2 = GRU(h)  # Default should be 'tanh'

Upon checking the source code, it seems like the encoder_activation parameter might not be properly utilized or set within the class.
Could you please look into this? Thank you for your assistance!

**Comment by marcopeix** [comment]
Hello! PyTorch has frozen the activation function for GRU. Therefore, we are going to deprecate the argument and remove it in a future version.
