### ISSUE TITLE
'NeuralForecast' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by wwulfric** [Nixtla/neuralforecast#798]
### What happened + What you expected to happen

The example for transfer learning cannot work
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-19-3e6f2d2f71fb>](https://localhost:8080/#) in <cell line: 1>()
----> 1 Y_hat_df = fcst2.predict(df=Y_train_df).reset_index()
      2 Y_hat_df.head()

[/usr/local/lib/python3.10/dist-packages/neuralforecast/core.py](https://localhost:8080/#) in predict(self, df, static_df, futr_df, sort_df, verbose, **data_kwargs)
    338                 df=df, static_df=static_df, sort_df=sort_df, scaler_type=None
    339             )
--> 340             dataset.scalers_ = self.dataset.scalers_
    341             dataset._transform_temporal()
    342         else:

AttributeError: 'NeuralForecast' object has no attribute 'dataset'

https://colab.research.google.com/github/Nixtla/neuralforecast/blob/main/nbs/examples/Transfer_Learning.ipynb#scrollTo=5eLU1eusHM5n  

<img width="1534" alt="image" src="https://github.com/Nixtla/neuralforecast/assets/8315997/5ead01da-b53f-421c-8ecf-97c80e370fbc">

### Versions / Dependencies

neuralforecast-1.6.4
datasetsforecast-0.0.8
python 3.10

### Reproduction script

https://colab.research.google.com/github/Nixtla/neuralforecast/blob/main/nbs/examples/Transfer_Learning.ipynb#scrollTo=RgNGBUbfHM5j

uncomment 
```
!pip install neuralforecast 
!pip install datasetsforecast
```
and execute all

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey @wwulfric, thanks for using neuralforecast. This bug was introduced recently, we'll work on it. In the meantime you can change the save method to use `save_dataset=True` and you should be able to run it. Sorry for the troubles.
