### ISSUE TITLE
Broken link on landing README.md

### ISSUE THREAD

**Issue by Tagar** [Nixtla/neuralforecast#803]
### Description

Broken link in the landing page under Highlights 

Improve accuracy and speed over classic ARIMA/ETS in two lines of code. Check the experiments [here](https://github.com/Nixtla/neuralforecast/blob/main/xXmissingXx).

https://github.com/Nixtla/neuralforecast#--highlights

### Link

https://github.com/Nixtla/neuralforecast#--highlights

**Comment by MMenchero** [comment]
This issue has been fixed since the line that had the broken link has been removed. I suggest we close it.
