### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by hberande** [Nixtla/neuralforecast#806]
Please help me to solve below error:- 
ImportError: cannot import name 'MLP' from 'neuralforecast.models' (C:\Users\41452\AppData\Local\anaconda3\envs\FCST\Lib\site-packages\neuralforecast\models\__init__.py)

**Comment by jmoralez** [comment]
Hey @hberande, thanks for using neuralforecast. Can you provide which neuralforecast version are you using and the command that you're running?

**Comment by hberande** [comment]
Hi @jmoralez, I have used !pip install neuralforecast==1.6.4 shown on the https://pypi.org/project/neuralforecast/0.0.6/

**Comment by hberande** [comment]
Also, Python version is 3.11.5

**Comment by jmoralez** [comment]
Can you try using `%pip` instead of `!pip` or even better using `!conda` for your installation? Seems like you're in a conda environment and using `!pip` may not install in the correct place.
