### ISSUE TITLE
[AutoNHITS,AutoRNN,AutoLSTM,AutoMLP,AutoDilatedRNN]  ValueError: invalid literal for int() with base 10: '216 (1)'

### ISSUE THREAD

**Issue by ams015** [Nixtla/neuralforecast#815]
### What happened + What you expected to happen

While doing hyperparameter selection with AutoNHITS,AutoRNN,AutoLSTM,AutoMLP,AutoDilatedRNN , I expect the process to finish.
For some point after it starts and does it, eventually this error appears for each model.
ValueError                                Traceback (most recent call last)
[<ipython-input-14-5909163196c3>](https://localhost:8080/#) in <cell line: 20>()
     18 models=models2,
     19 freq='b')
---> 20 nf.fit(df=Y_train_df)

12 frames
[/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/tensorboard.py](https://localhost:8080/#) in _get_next_version(self)
    244             if _is_dir(self._fs, d) and bn.startswith("version_"):
    245                 dir_ver = bn.split("_")[1].replace("/", "")
--> 246                 existing_versions.append(int(dir_ver))
    247         if len(existing_versions) == 0:
    248             return 0

ValueError: invalid literal for int() with base 10: '216 (1)'

### Versions / Dependencies

Python 3.10.12, neuralforecast 1.6.4, on google colab

### Reproduction script

from neuralforecast.tsdataset import TimeSeriesDataset
from neuralforecast.utils import AirPassengers, AirPassengersPanel, AirPassengersStatic
import pandas as pd
from neuralforecast import NeuralForecast
from ray import tune
from neuralforecast.auto import AutoNHITS,AutoRNN,AutoLSTM,AutoMLP,AutoDilatedRNN
from neuralforecast.losses.pytorch import MAE

#AirPassengersPanel['y'] = AirPassengersPanel['y'] + 10
Y_train_df = AirPassengersPanel[AirPassengersPanel.ds<AirPassengersPanel['ds'].values[-12]] # 132 train
Y_test_df = AirPassengersPanel[AirPassengersPanel.ds>=AirPassengersPanel['ds'].values[-12]].reset_index(drop=True) # 12 test

models2= [AutoLSTM(h=15,
loss=MAE(),
config=None,
num_samples=2,gpus=1 )]
nf= NeuralForecast(
models=models2,
freq='b')
nf.fit(df=Y_train_df)

models2= [AutoRNN(h=15,
loss=MAE(),
config=None,
num_samples=2,gpus=1 )]
nf= NeuralForecast(
models=models2,
freq='b')
nf.fit(df=Y_train_df)

models2= [AutoNHITS(h=15,
loss=MAE(),
config=None,
num_samples=2,gpus=1 )]
nf= NeuralForecast(
models=models2,
freq='b')
nf.fit(df=Y_train_df)

models2= [AutoMLP(h=15,
loss=MAE(),
config=None,
num_samples=2,gpus=1 )]
nf= NeuralForecast(
models=models2,
freq='b')
nf.fit(df=Y_train_df)

models2= [AutoDilatedRNN(h=15,
loss=MAE(),
config=None,
num_samples=2,gpus=1 )]
nf= NeuralForecast(
models=models2,
freq='b')
nf.fit(df=Y_train_df)

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey @ams015, thanks for using neuralforecast. Can you include the full stacktrace?

**Comment by ams015** [comment]
for some reason the issue has gone away. might have been a c
