### ISSUE TITLE
Load Model NHITS|Core

### ISSUE THREAD

**Issue by pmelo** [Nixtla/neuralforecast#817]
### What happened + What you expected to happen

Having create an NHITS model, able to fit and to predict, and save the model.
When I load the model and predict, receive this error:

....

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-8adfd926-64bf-41db-939e-3f917799867b/lib/python3.10/site-packages/yaml/representer.py:330, in Representer.represent_object(self, data)
    328     listitems = list(listitems)
    329 if dictitems is not None:
--> 330     dictitems = dict(dictitems)
    331 if function.__name__ == '__newobj__':
    332     function = args[0]

ValueError: dictionary update sequence element #0 has length 1; 2 is required
....

Any idea?

### Versions / Dependencies

torchvision==0.16
neuralforecast==1.6.4
torchmetrics==1.2.0
pandas==1.4.4
protobuf==3.19.4
PyYAML==5.4.1

### Reproduction script

model2=NeuralForecast.load("/nhits_study_20231103144339")
model2.predict(futr_df = ts_eval)

### Issue Severity

High: It blocks me from completing my task.

**Comment by pmelo** [comment]
I was able to isolate the issue, maybe will be helpful to some one
`
    trainer_kwargs = {
        'accelerator': 'gpu',
        'enable_progress_bar' : verbose,
        "callbacks": [EarlyStopping("train_loss", min_delta=0.0001, patience=early_stop_patience_steps, verbose=verbose)],`

and then build the model
with parameter **trainer_kwargs

**Comment by jmoralez** [comment]
Hey @pmelo, thanks for using neuralforecast. Can you provide the configuration of the NHITS and the command you used to save it?
