### ISSUE TITLE
The picture link in tutorial on how to add new models to NeuralForecast is broken.

### ISSUE THREAD

**Issue by Axl-zhang** [Nixtla/neuralforecast#819]
### Description

Hi, the picture below the Example: simplified MLP model is broken, can you fix it?
(https://nixtla.mintlify.app/neuralforecast/examples/how_to_add_models.html#example-simplified-mlp-model)

Thanks  :)

### Link

https://nixtla.mintlify.app/neuralforecast/examples/how_to_add_models.html#example-simplified-mlp-model

**Comment by Axl-zhang** [comment]
This one: https://mintlify.s3-us-west-1.amazonaws.com/nixtla/neuralforecast/neuralforecast/imgs_models/mlp.png

**Comment by jmoralez** [comment]
Thanks for raising this. We've fixed the image path.
