### ISSUE TITLE
[TimesNet] Using monday weekly data

### ISSUE THREAD

**Issue by rjguedes8** [Nixtla/neuralforecast#820]
### What happened + What you expected to happen

I have a dataset with 264 time series and weekly data.
I'm trying to use TimesNet to forecast all of them with static and dynamic covariates.

However, I get an error when using the predict function with `freq='W'` that says `**ValueError: `futr_df` must have one row per id and ds in the forecasting horizon (16).**`. I checked and all of them have 16 observations and the ds is also ok, I have 16 consecutive mondays.
Nevertheless, if I change the `freq` argument to `W-MON`, the error does not happen but the predictions are NANs...
Any idea how to solve this issue?

### Versions / Dependencies

neuralforecast==1.6.4
python 3.10

### Reproduction script

just try to forecast weekly data with several time series

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Hey @rjguedes8, thanks for using neuralforecast. Can you provide a reproducible example? The following works fine:
```python
from utilsforecast.data import generate_series
from neuralforecast import NeuralForecast
from neuralforecast.losses.pytorch import DistributionLoss
from neuralforecast.models import TimesNet

data = generate_series(10, freq='W-MON')

model = TimesNet(
    h=4,
    input_size=8,
    hidden_size=16,
    conv_hidden_size = 32,
    loss=DistributionLoss(distribution='Normal', level=[80, 90]),
    learning_rate=1e-3,
    max_steps=5,
    val_check_steps=50,
    early_stop_patience_steps=2
)
nf = NeuralForecast(models=[model], freq='W-MON')
nf.fit(data, val_size=4)
nf.predict()
```

**Comment by rjguedes8** [comment]
Hey José, thank you for your quick response!

I tried to run your code and got this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[106], line 8
      6 freq = 'W-MON'
      7 h = 4
----> 8 data = generate_series(10, freq=freq, n_static_features=2)
      9 valid = data.groupby('unique_id', observed=True).tail(h)
     10 train = data.drop(valid.index)

File /opt/conda/lib/python3.10/site-packages/utilsforecast/data.py:72, in generate_series(n_series, freq, min_length, max_length, n_static_features, equal_ends, with_trend, static_as_categorical, n_models, level, engine, seed)
     70 available_frequencies = seasonalities.keys()
     71 if freq not in available_frequencies:
---> 72     raise ValueError(
     73         f"Currently soported frequencies are: {available_frequencies}, got {freq}"
     74     )
     76 rng = np.random.RandomState(seed)
     77 series_lengths = rng.randint(min_length, max_length + 1, n_series)

ValueError: Currently soported frequencies are: dict_keys(['D', 'M']), got W-MON
```
What is the package version that you are using? I'm using 1.6.4

**Comment by jmoralez** [comment]
Can you upgrade your utilsforecast version? `pip install -U utilsforecast`

**Comment by rjguedes8** [comment]
it's working now, thanks :)
