### ISSUE TITLE
[Model] Using external variable in Auto Models 

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/neuralforecast#821]
### What happened + What you expected to happen

1. Using AutoNHITS with parameter future_exog_list, and got an error. 
<command-2310414706428830> in forecast_neuralforecast_ext(Y_df_train, horizon, X_df_train, X_df_test)
    415               # encoder_hidden_size=64,       # Defines the size of the hidden state of the LSTM
    416               # decoder_hidden_size=64,),     # Defines the number of hidden units of each layer of the MLP decoder
--> 417           AutoNHITS(h=horizon,                   # Forecast horizon
    418                 #input_size=2 * horizon,      # Length of input sequence
    419                 config = config_nhits,

TypeError: __init__() got an unexpected keyword argument 'future_exog_list'

2. NHITS can accept external variables, so I thought AutoNHits would accept as well, however it isn't true?? 

Also if a variable is varying, but present both for past, and future then it should be specified in both places?  

### Versions / Dependencies

1.6.4

### Reproduction script

config_nhits = {
    "input_size": tune.choice([14, 14*2, 14*4]),              # Length of input window
    "start_padding_enabled": True,
    "n_blocks": 5*[1],                                              # Length of input window
    "mlp_units": 5 * [[64, 64]],                                  # Length of input window
    "n_pool_kernel_size": tune.choice([5*[1], 5*[2], 5*[4],         
                                      [8, 4, 2, 1, 1]]),            # MaxPooling Kernel size
    "n_freq_downsample": tune.choice([[8, 4, 2, 1, 1],
                                      [1, 1, 1, 1, 1]]),            # Interpolation expressivity ratios
    "learning_rate": tune.loguniform(1e-4, 1e-2),                   # Initial Learning rate
    "scaler_type": tune.choice([None, 'robust', 'standard']),                             # Scaler type
    "max_steps": tune.choice([1000]),                               # Max number of training iterations
    "batch_size": tune.choice([1, 4, 10]),                          # Number of series in batch
    "windows_batch_size": tune.choice([128, 256, 512]),             # Number of windows in batch
    "random_seed": tune.randint(1, 20),                             # Random seed
}

    models = [#LSTM(h=horizon,                    # Forecast horizon
              # max_steps=500,                # Number of steps to train
              # scaler_type='standard',       # Type of scaler to normalize data
              # encoder_hidden_size=64,       # Defines the size of the hidden state of the LSTM
              # decoder_hidden_size=64,),     # Defines the number of hidden units of each layer of the MLP decoder
          AutoNHITS(h=horizon,                   # Forecast horizon
                #input_size=2 * horizon,      # Length of input sequence
                config = config_nhits, 
                loss = MAE(), #MQLoss(), 
                num_samples = 5, 
                future_exog_list = ['exog1'], 
                hist_exog_list = ['exog2'], 
                stat_exog_list = ['x', 'y'], 
                max_steps=100,               # Number of steps to train
                n_freq_downsample=[2, 1, 1]) # Downsampling factors for each stack output
          ]
    nf = NeuralForecast(models=models, freq='W-SAT')
    nf.fit(df=pd.merge(Y_df_train, X_df_train, on = ['unique_id', 'ds']), val_size = horizon)

    nf_preds_df = nf.predict()
    nf_fitted_df = nf.predict_insample(step_size = horizon)

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey @iamyihwa, thanks for using neuralforecast. I believe this is the same issue as #791. For auto models you have to provide them through the config.

Yes, if a feature is present in both times you should specify it as historic and future.

**Comment by jmoralez** [comment]
Hey @iamyihwa, just want to correct my previous statement. If a feature is present in both times you should specify it as future only.
