### ISSUE TITLE
Variable Length & Range Time Series as Input

### ISSUE THREAD

**Issue by SinghJivjot** [Nixtla/neuralforecast#846]
### Description

How does the current Input Data format work? If i want to model a lot of Time series together, does the Length of each Serie need to be of the same duration, also what about Time Range of each ID? (Given that I have performed per-Serie Gap filling)

### Use case

unique_id |           ds            |     y     |
------------------------------------------------------------------------------------------------------------------
363069     |    2016-06-14    |    2.0   |
363069     |    2016-06-15    |    3.0   |
363069     |    2016-06-16    |    1.0   |
645127     |    2018-03-01    |    6.0   |
645127     |    2018-03-02    |    4.0   |

**Comment by jmoralez** [comment]
Hey @SinghJivjot, thanks for using neuralforecast. About your question, there's no restriction on the length of each serie or their time ranges as long as they have enough samples to run the computations.

Could you please open separate issues for the other suggestions?

**Comment by SinghJivjot** [comment]
Thanks for the clarification
