### ISSUE TITLE
PatchTST does not yet support historical exogenous variables

### ISSUE THREAD

**Issue by Gardenimmortal** [Nixtla/neuralforecast#847]
### What happened + What you expected to happen

PatchTST does not support covariate-assisted prediction, which I find unfortunate to be a significant reduction in prediction performance

### Versions / Dependencies

neuralforecast 1.6.4

### Reproduction script

    952         if hist_exog_list is not None:
--> 953             raise Exception(
    954                 "PatchTST does not yet support historical exogenous variables"
    955             )

### Issue Severity

None

**Comment by rd1886** [comment]
The same goes for futr_exogenous_list. According to the documentation [here](https://nixtlaverse.nixtla.io/neuralforecast/models.patchtst.html), it appears that PatchTST supports futr_exogenous_list. However, when I attempt to run the model with futr_exogenous_list, I encounter the following error:

Exception: PatchTST does not yet support future exogenous variables

**Comment by Zhangxixiang77** [comment]
I'm having the same problem, obviously the parameter is there but unfortunately it's telling me it's not supported. “PatchTST does not yet support historical exogenous variables”

**Comment by elephaint** [comment]
PatchTST (the architecture) does not support additional exogenous inputs afaik, that's why the exception is raised. Usually if it is not supported by the original architecture we will not include it, as it may require us to substantially deviate from the original work (adding exogenous to an architecture is quite tricky).

There are many other options that may provide equal or better forecasting performance at lower computational cost if you need to use exogenous variables, e.g. NHITS, TSMixerx, BiTCN.

Hope this helps.

**Comment by deiping** [comment]
Hello, sir. It seems that patchtst is inherently multivariate. Additionally, patchtst appears to perform well with short time series, as indicated by tslib.

**Comment by elephaint** [comment]
> Hello, sir. It seems that patchtst is inherently multivariate. Additionally, patchtst appears to perform well with short time series, as indicated by tslib.

This doesn't relate to the issue at hand: multivariate/univariate has nothing to do with a model being able to handle exogenous covariates.

**Comment by sultanfsn** [comment]
> PatchTST (the architecture) does not support additional exogenous inputs afaik, that's why the exception is raised.

Hey! Appreciate all the work, but I think you should update the [docs](https://nixtlaverse.nixtla.io/neuralforecast/models.patchtst.html) and not include it there if this was the case.
