### ISSUE TITLE
Why does the training process stop without reporting any error? (Both on CPU/GPU)

### ISSUE THREAD

**Issue by ZihanChen1995** [Nixtla/neuralforecast#848]
### What happened + What you expected to happen

Hi, thank you for this great library! I am testing the NeuralForecast examples with my own dataset. However, when I fit the data using `nf.fit()`, **the training process stops without reporting any errors**. May I ask why this happens and how I can solve it? Any hints for debugging would be really appreciated!

(I tested it on both GPU and CPU, but the issue occurs on both.)

---
### Sample Data: 

[Link to Download](https://drive.google.com/drive/folders/1C8sNHnF-OF_ZyuiMBENRY_JW2pGG9pW6?usp=sharing)

###  Stop Message:
<img width="1054" alt="Screenshot 2024-01-02 at 10 05 10 PM" src="https://github.com/Nixtla/neuralforecast/assets/36064256/fb9e31fa-4a19-422e-bfeb-82b1adfc386a">

### Versions / Dependencies

```
!pip install -q neuralforecast

import neuralforecast
neuralforecast.__version__

>>> 1.6.4
```

### Code:
```
# load data
tem_df = pd.read_csv("test_df.csv", index_col=0)
tem_df["ds"] = pd.to_datetime(tem_df["ds"])

horizon = 30

# Try different hyperparmeters to improve accuracy.
models = [LSTM(h=horizon,                    # Forecast horizon
               max_steps=1000,                # Number of steps to train
               scaler_type='standard',       # Type of scaler to normalize data
               encoder_hidden_size=128,       # Defines the size of the hidden state of the LSTM
               decoder_hidden_size=128,
               accelerator="gpu",
               input_size = horizon,)     # Defines the number of hidden units of each layer of the MLP decoder
]

nf = NeuralForecast(models=models, freq='D')

nf.fit(df=tem_df,
       verbose=True,)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by cchallu** [comment]
Hi @ZihanChen1995. Thanks for using the library! There is no issue in your training; it just ended because it reached the max number of iterations, given by `max_steps=1000`. We prefer to specify training with steps, but PyTorch Lightning only reports progress with epoch bars so sometimes it will finish in the middle of one. If you want to train for longer simply increase the `max_steps`. Hope this helps!

**Comment by candalfigomoro** [comment]
@ZihanChen1995 Basically, in your specific case (from the screenshot you posted), if you want to run the training for full epochs and see the green progress bar, you have to use a number of steps that is a multiple of 102.

**Comment by ZihanChen1995** [comment]
Thank you for your comments! Yes, this is successfully solved now.
