### ISSUE TITLE
[Model] Not able to load a saved model 

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/neuralforecast#855]
### What happened + What you expected to happen

I was saving a trained model, and trying to load it, but got an error. 

```
nf.save(path='./checkpoints/test_run2/',
        model_index=None,
        overwrite=True,
        save_dataset=True)

nf2 = NeuralForecast.load(path='./checkpoints/test_run2/')


```
The error message I am getting is 
KeyError: 'timesnet'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File <command-2274526657342161>, line 1
----> 1 nf2 = NeuralForecast.load(path='./checkpoints/test_run2/')

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-673311d2-3e2d-4e5c-8f2a-e93539772984/lib/python3.10/site-packages/neuralforecast/core.py:758, in NeuralForecast.load(path, verbose, **kwargs)
    755 for model in models_ckpt:
    756     model_name = model.split("_")[0]
    757     models.append(
--> 758         MODEL_FILENAME_DICT[model_name].load_from_checkpoint(
    759             f"{path}/{model}", **kwargs
    760         )
    761     )
    762     if verbose:
    763         print(f"Model {model_name} loaded.")

KeyError: 'timesnet'

When i look what is in the directory , timesnet_0 is present instead of timesnet .. 
```
!ls checkpoints/test_run2
```

### Versions / Dependencies

1.6.4

### Reproduction script

from neuralforecast.losses.pytorch import RMSE

from neuralforecast import NeuralForecast
from neuralforecast.auto import TimesNet, AutoNHITS, AutoLSTM, AutoRNN
from neuralforecast.models import Informer, Autoformer, FEDformer, PatchTST

horizon = 52
nf = NeuralForecast(
    models= [
      # AutoNHITS( h= horizon, config = None, loss=RMSE(), backend='optuna'),
        TimesNet (input_size = 2*horizon, # 4*time_len,
                  top_k = 3,                                                   # Number of periods (for FFT).
                  num_kernels = 3,                                             # Number of kernels for Inception module
                  batch_size = 2,                                              # Number of time series per batch
                  windows_batch_size = 32,  # Number of windows per batch
                  learning_rate = 0.001,
                  h = horizon,
                  loss=RMSE(),
                  start_padding_enabled = True, 
                  scaler_type = 'robust'
                #  futr_exog_list = ['Holiday_Flag', 'Temperature', 'Fuel_Price', 'CPI', 'Unemployment'], # Future exogenous variables                                       )                                                # Horizon
                )
    ],
    freq='W-SAT'
  )

nf.fit(train_df) 
nf.save(path='./checkpoints/test_run2/',
        model_index=None,
        overwrite=True,
        save_dataset=True)

nf2 = NeuralForecast.load(path='./checkpoints/test_run2/')

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey @iamyihwa, thanks for the report. I believe we're missing a key here https://github.com/Nixtla/neuralforecast/blob/68affcd39e65f4dd98fe9b72a4ff748d23632dc3/neuralforecast/core.py#L139
I'll make a PR to fix it.

**Comment by jmoralez** [comment]
In the meantime you should be able to save an AutoTimesNet model, you can fix most of the arguments and set `num_samples=1`.

**Comment by iamyihwa** [comment]
You mean TimesNet Model? 
I am having some issues with the Auto versions of the models in databricks currently (created an [issue](https://github.com/Nixtla/neuralforecast/issues/854)).  
Sure! Will try that!

**Comment by iamyihwa** [comment]
@jmoralez   May we reopen this issue? I am still having issues. 

I have installed main branch by 'pip install git+https://github.com/Nixtla/neuralforecast.git@main' 

After saving the model. 


``` 
nf.save(path='./checkpoints/test_run/',
        model_index=None, 
        overwrite=True,
        save_dataset=True)

nf2 = NeuralForecast.load(path='./checkpoints/test_run/')
``` 


and I am getting this error. 
(timesnet-exg' is lowered version of alias name of the models I have used.) 

[rank: 0] Seed set to 1
[rank: 0] Seed set to 1
KeyError: 'timesnet-exg'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File <command-3963784586171241>, line 1
----> 1 nf2 = NeuralForecast.load(path='./checkpoints/test_run/')
      2 #Y_hat_df = nf2.predict().reset_index()
      3 #Y_hat_df.head()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-96e27a02-5fe5-43cc-9fd8-10529b1abdfa/lib/python3.10/site-packages/neuralforecast/core.py:1056, in NeuralForecast.load(path, verbose, **kwargs)
   1053 for model in models_ckpt:
   1054     model_name = model.split("_")[0]
   1055     models.append(
-> 1056         MODEL_FILENAME_DICT[model_name].load_from_checkpoint(
   1057             f"{path}/{model}", **kwargs
   1058         )
   1059     )
   1060     if verbose:
   1061         print(f"Model {model_name} loaded.")

Model description. 
``` 
 TimesNet (input_size = 2*horizon, # 4*time_len,
                  top_k = 3,                                                   # Number of periods (for FFT).
                  num_kernels = 3,                                             # Number of kernels for Inception module
                  batch_size = 2,                                              # Number of time series per batch
                  windows_batch_size = 32,  # Number of windows per batch
                  learning_rate = 0.001,
                  h = horizon,
                  loss=HuberMQLoss(quantiles=quantiles),  # RMSE(),
                  start_padding_enabled = True, 
                  scaler_type = 'robust', 
                  alias = 'TimesNet-Exg',
                         )                                                # Horizon
                ), 
``` 
It is one of the name I've given to the

**Comment by iamyihwa** [comment]
In the current released version (not in the main branch), when I am not using alias, the problem goes away. 
It is when I am using alias I am getting the error. 

```
      GRU(h=horizon,input_size=-1,
                loss=RMSE(),
                scaler_type='robust',
                encoder_n_layers=2,
                encoder_hidden_size=128,
                context_size=10,
                decoder_hidden_size=128,
                decoder_layers=2,
                max_steps=200,
                alias = 'GRU-1',
                )
``` 

I defined two models, with and without the alias row (alias = 'GRU-1'), when i didn't have alias, model saving and loading (and continue training) worked fine, however with alias specified was getting the error. 

KeyError: 'gru-1'

So for my use case, will use it without the alias. 
Thanks again for the help!

**Comment by jmoralez** [comment]
We should support saving models with aliases, so I'm reopening this until we fix that. Thanks for the report!
