### ISSUE TITLE
Adding support for DeepNPTS model

### ISSUE THREAD

**Issue by Jonathan-87** [Nixtla/neuralforecast#857]
### Description

It would be useful to add the Deep Non-Parametric Time Series forecaster (DeepNPTS). You can find the paper here (https://arxiv.org/pdf/2312.14657.pdf) and the model is included in GluonTS. DeepNPTS is a strong baseline and is competitive to complex models.

**Comment by elephaint** [comment]
Hi,

I've worked on this a bit and have a working version, but DeepNPTS is either slow (the version that use a Discrete distribution) or very unstable (the smooth version that uses weighted Gaussian Mixtures). 

So at this moment a bit pondering whether to include it in our library as its either extremely slow or highly unstable. Agree that it's a nice baseline though, just not yet sure if it adds suffcient value to have the model in Neuralforecast.

**Comment by elephaint** [comment]
> Hi, thank you for this follow up and well I understand the concerns. Do I understand that I can give it a try ?

Not yet, I'll let you know.

**Comment by elephaint** [comment]
@Jonathan-87 DeepNPTS is part of the last release (1.7.2)
