### ISSUE TITLE
[tsdataset]`batch_size` not work and always get batch_size = 1

### ISSUE THREAD

**Issue by MrTangsai** [Nixtla/neuralforecast#860]
### What happened + What you expected to happen

Hi, I set model param with `batch_size=32`, but I saw the source code, I found that not work, just return `batch_size = 1` when step into `training_step` everytime, I think that probable reason is `RandomSampler` recognize `TimeSeriesDataset` length is 1 ?

### Versions / Dependencies

- neuralforecast: 1.6.4
- python: 3.8.16
- os: Ubuntu

### Reproduction script

the code is below:
```python
import pandas as pd 
import pytorch_lightning as pl
from neuralforecast import NeuralForecast
from neuralforecast.models import LSTM
# from neuralforecast.tsdataset import TimeSeriesDataModule
from neuralforecast.utils import AirPassengersDF

Y_df = AirPassengersDF # Defined in neuralforecast.utils
class PrintBatchSizeCallback(pl.Callback):
    def on_train_batch_start(self, trainer, pl_module, batch, batch_idx,):
        print(f"Batch Size: {batch['temporal'].size()}")

nf = NeuralForecast(
    models=[LSTM(h=12, batch_size=32, max_steps=500, scaler_type='standard', encoder_hidden_size=64, decoder_hidden_size=64, 
                 fast_dev_run=1, 
                 callbacks=[PrintBatchSizeCallback()]
                 )],
    freq='M'
    )
nf.fit(Y_df)
```

and the print callback is below:
`Batch Size: torch.Size([1, 2, 144])`

I think it should be `torch.Size([32, 2, 144])`

![image](https://github.com/Nixtla/neuralforecast/assets/27365618/c6b261b3-7ce8-4069-8800-d8ba7ec65fd8)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by cchallu** [comment]
Hi @MrTangsai ! `batch_size` is the maximum number of time series that will be sampled at each training iteration, then the `windows_batch_size` determine the number of particular windows. The sampled time series are not repeated (to improve memory efficiency). AirPassengers only have 1 time series, so it will always return 1 time series.

**Comment by MrTangsai** [comment]
Understood, I thought `batch_size` means repeat `batch_size` time series and then resample the `input_size`  length sequence to model. Otherwise, if there is not enough time series, the `batch_size` can easily lead to ambiguity, as many scenarios only have one time series
