### ISSUE TITLE
switch to Ruff instead of `flake8`

### ISSUE THREAD

**Issue by Borda** [Nixtla/neuralforecast#868]
### Description

Recently [Ruff](https://github.com/astral-sh/ruff) has become very popular among also mainstream projects for:
- much faster, they say 70x
- integrate several other tools under one roof, such as isort or bandit

### Use case

if you are fine with this change I am happy to send such PR for review... :rabbit:

**Comment by jmoralez** [comment]
Hey @Borda, thanks for the suggestion. This is something we've been meaning to do, feel free to open a PR.
