### ISSUE TITLE
using Black formatting?

### ISSUE THREAD

**Issue by Borda** [Nixtla/neuralforecast#872]
### Description

I have noticed on several places in the project to `black` formatting, but it is nowhere used or checked, so what is the case? Shall it be Black formatted or have a reference removed from it?

### Use case

If the Back shall be used, I suggest adding/using - pre-commit, which would facilitate this formatting, and eventually, we can integrate all linters in this job...

**Comment by jmoralez** [comment]
Hey. The code is formatted when we export it from the notebooks, you can see the config here: https://github.com/Nixtla/neuralforecast/blob/dc030bb3a35008144cbd682dcd3f10e1cd4f1057/settings.ini#L28

**Comment by Borda** [comment]
> The code is formatted when we export it from the notebooks; you can see the config here

Yes, that is what I found... when exported, do you mean when the package is built or notebooks are converted? I'm not sure if I got what you mean...

**Comment by jmoralez** [comment]
We use [nbdev](https://nbdev.fast.ai/) to develop the library, so we write the code in [notebooks](https://github.com/Nixtla/neuralforecast/tree/main/nbs) and when we export them (extract all cells with the `#| export` tag into the python files) it applies the black formatter. So the code in the neuralforecast folder should always be formatted.
