### ISSUE TITLE
[Core] Check input for NaNs 

### ISSUE THREAD

**Issue by jmoralez** [Nixtla/neuralforecast#890]
### Description

If any of the inputs contains NaNs with `available_mask = 1` they will be used for training and can be propagated to the predictions or produce failures in training. We should check that the target, exogenous and static features don't have any NaNs for the rows where `available_mask = 1` and provide an informative error message if they do.

### Use case

This will help saving time when trying to train models on invalid inputs, since it will fail before starting the training process.

**Comment by cchallu** [comment]
@quest-bot stash 100

**Comment by JQGoh** [comment]
@quest-bot embark

**Comment by jmoralez** [comment]
Fixed by #894
