### ISSUE TITLE
Example notebooks

### ISSUE THREAD

**Issue by gdevos010** [Nixtla/neuralforecast#91]
**Is your feature request related to a problem? Please describe.**
I see some cool work here, but it's hard to understand how to use the project without some examples.

**Describe the solution you'd like**
Add some example notebooks showing off how to use the different features in the project.

**Describe alternatives you've considered**
any other form of documentation 

**Additional context**

**Comment by FedericoGarza** [comment]
@all-contributors please add @gdevos010 for ideas

**Comment by mergenthaler** [comment]
@gdevos010, we updated the ReadMe and included an example Notebook. Does that work?

**Comment by gdevos010** [comment]
Yes, that notebook is very helpful. I also see the documentation has examples for each model. I don't believe there was when I created the issue, but I could be wrong.

Keep up the great work, Im following the project with great interest.
