### ISSUE TITLE
[BUG] `LSTM` model does not have `encoder_activation` parameter but contains in the docstring

### ISSUE THREAD

**Issue by yarnabrina** [Nixtla/neuralforecast#910]
I've noticed that `LSTM` model does not have `encoder_activation` as an argument in `__init__` but it's documented in the docstring.

https://github.com/Nixtla/neuralforecast/blob/7f69d7898fe01fc802cab8d08c590df31944fd85/neuralforecast/models/lstm.py#L31

**Comment by jmoralez** [comment]
I think this is the same as #426

**Comment by yarnabrina** [comment]
Yes. If you want, this can be closed as duplicate.

Will you accept a PR removing the line from docstring? The alternative by adding a new argument (similar to how it's there for RNN) will likely be a breaking change for users relying on order of keyword arguments.

**Comment by jmoralez** [comment]
> Will you accept a PR removing the line from docstring?

Yes, it doesn't seem to be used.
