### ISSUE TITLE
HINT outputs not Coherent

### ISSUE THREAD

**Issue by BWBarber** [Nixtla/neuralforecast#945]
### What happened + What you expected to happen

When running HINT, I expect the sum of lower level forecasts to be coherent with higher level forecasts. That is not happening.

### Versions / Dependencies

1.7.0

### Reproduction script

[Google Colab Demonstration of error](https://colab.research.google.com/drive/18CUa9eSyombCAa8Tl8HdJqg4AMchEIoe#scrollTo=kioJ9NJEeDkd)

### Issue Severity

High: It blocks me from completing my task.

**Comment by elephaint** [comment]
Thanks for reporting - a solution to the issue has been proposed in #964.

If the solution is merged, this issue will be closed.
