### ISSUE TITLE
Implementing TIDE in neuralforecast

### ISSUE THREAD

**Issue by valeman** [Nixtla/neuralforecast#970]
### Description

Did the team consider implementing TIDE? is seems to be getting a lot of traction recently confirming its performance vis-a-vis the one in TIDE paper and it has been also implemented in Darts. Would be great to have it in neuralforecast.

Long-term Forecasting with TiDE: Time-series Dense Encoder https://arxiv.org/abs/2304.08424

**Comment by elephaint** [comment]
Sure, we'll have a look!

**Comment by candalfigomoro** [comment]
Duplicate of Issue #610
