### ISSUE TITLE
when to surport KANS?

### ISSUE THREAD

**Issue by luoolu** [Nixtla/neuralforecast#992]
### Description

KANs have faster scaling than MLPs. KANs have better accuracy than MLPs with fewer parameters.

**Comment by elephaint** [comment]
Thanks for the suggestion. I think KANs are a nice scientific path and applying it to forecasting could be an interesting scientific venue to pursue.

I don't think the existing evidence about KANs support your statements, though. Your statements are very generic - as if they would apply to any and all problem settings - but the [recent KAN paper](https://arxiv.org/pdf/2404.19756) to which I believe you are referring to doesn't offer the evidence to suggest the generality of your statements. 

For now, we'll keep an eye on how KANs perform in real-world problems, and we maybe experiment with them ourselves too. If we find that the performance of KANs for forecasting tasks is a worthwile contribution to NeuralForecast, it may make sense to include them.

Please provide (preferably peer-reviewed) evidence to the contrary if I'm mistaking in any of my statements above.
